<?php

namespace Database\Seeders;

use App\Models\FishFamily;
use App\Models\FishSpecies;
use Illuminate\Database\Seeder;
use Illuminate\Support\Collection;

class FishSpeciesSeeder extends Seeder
{
    /**
     * The species of the national catch coding sheet, as
     * [code, scientific name, English name, Gulf local name, Red Sea local name].
     *
     * Two codes reach us mistyped and are filed here as the sequence intends them:
     * Caranx sexfasciatus arrives as 39011 and is seeded as 3911, and the Carangidae
     * catch-all repeats 3923, which is seeded as 3924.
     *
     * @var list<array{0: int, 1: string, 2: ?string, 3: ?string, 4: ?string}>
     */
    private const SPECIES = [
        [1001, 'Chirocentrus nodus', 'Whitefin wolf - herrings', 'الحف', 'ابوسيف'],
        [1002, 'Chirocentrus dorab', 'Dorab wolf - herrings', null, 'درب / نصل / أبوسيف /ام السردين'],
        [1101, 'Chanos chanos', 'Milkfish', 'خني / بونجي', 'سلماني/ سليماني/ مخنثة'],
        [1201, 'Bothus pantherinus', 'Leopard flounder', 'خوفعة', 'حصني البحر/ غطاء موسى / ام جهة'],
        [1301, 'Arius thalassinus', 'Giant seacatfish', 'جيم / شيم', 'ابوشنب / كمل'],
        [1401, 'Saurida undosquamis', 'Brush tooth lizard fish', 'حاسوم', 'مكرونه هندي'],
        [1402, 'Saurida tumbil', 'Greater lizardfish', null, 'مكرونه مصري'],
        [1403, 'Trachinocephalus myops', 'Snakefish', null, 'مكرونة مخطط'],
        [1404, 'Synodontidae.nei', 'Lizardfish . nei.', 'انواع اخرى من الحاسوم', 'انواع اخرى من المكرونة'],
        [1501, 'Aethaloperca rogaa', 'Redmouth grouper', null, 'رقع، بنت الروبان، قط الروبان'],
        [1502, 'Cephalopholis argus', 'Peacock hind', null, 'كشر أبو بلحة، حبج ، أبو سعيد ، أبونقطة'],
        [1503, 'Cephalopholis hemistiktus', 'Halfspotted hind', 'سود / سبيتي / اشنينوه / سلور', 'أبوهويلي / حمروني'],
        [1504, 'Cephalopholis miniata', 'Coral hind', 'رفع / شبيه الناجل / شنينو', 'كشر أبو عدس / أبو نوارة / فرخ الناجل'],
        [1505, 'Epinephelus areolatus', 'Areolate grouper', 'لدن / قطوه', 'قماته'],
        [1506, 'Epinephelus caeruleopunctatus', 'Whitespotted grouper', 'برطام', 'كسيلان'],
        [1507, 'Epinephelus chlorostigma', 'Brownspotted grouper', null, 'مقيطة / كشر شون / أبوحرابة'],
        [1508, 'Epinephelus coioides', 'Orange - spotted grouper', 'بألول', 'كشر برتقالي النقاط'],
        [1509, 'Epinephelus epistictus', 'Dotted grouper', null, null],
        [1510, 'Epinephelus fasciatus', 'Blacktip grouper', null, 'كشر أبو لولو'],
        [1511, 'Epinephelus fuscoguttatus', 'Brown - marbled grouper', 'برطامة', 'كرشافة ، شهاوي/ حلال'],
        [1512, 'Epinephelus latifasciatus', 'Banded grouper', null, null],
        [1513, 'Epinephelus malabaricus', 'Malabar grouper', null, 'شهوه / فرخ توينه'],
        [1514, 'Epinephelus multinotatus', 'White - blotched grouper', 'بغل', null],
        [1515, 'Epinephelus morrhua', 'Comet grouper', null, 'كشر أبو لولو / كشر طينة'],
        [1516, 'Epinephelus pleekeri', 'Duskytail grouper', null, null],
        [1517, 'Epinephelus polyepis', 'Smalltooth grouper', null, null],
        [1518, 'Epinephelus polyphykadion', 'Camouflage grouper', 'هامور سمان', 'أبوخمام / حشرية / حبج / شهوان'],
        [1519, 'Epinephelus summana', 'Summan grouper', null, 'كشر مبلعط، ضبع ،برادي، أبو ظهير، خرنوع'],
        [1520, 'Epinephelus tauvina', 'Greasy grouper', 'هامور توينة', 'كشر توينة / حشرية / أبو نوم'],
        [1521, 'Plectropomus areolatus', 'Squaretail coralgrouper', null, 'طرادي'],
        [1522, 'Plectropomus pessuliferus', 'Roving coralgrouper', null, 'ناجل'],
        [1523, 'Variola louti', 'Yellow - edged lyretail', null, 'لوطي /شريف / ريشال'],
        [1524, 'Serranidae. nei', 'Groupers nei', 'أنواع أخرى من الهامور', 'أنواع أخرى من الكشر'],
        [1601, 'Aphareus rutilans', 'Rusty Jobfish', null, 'فارس'],
        [1602, 'Lutjanus argentimaculatus', 'Mangrove redsnapper', null, 'شعفن'],
        [1603, 'Lutjanus bohar', 'Two - spot redsnapper', 'شقر /نعيمي', 'بهار(كبير) /طمرة (صغير)'],
        [1604, 'Lutjanus gibbus', 'Humpback redsnapper', 'حمرا صابغ', 'عصمودي/ حمرا'],
        [1605, 'Lutjanus kasmira', 'Common bluestripe snapper', 'نيسرة زرقاء الخطوط', 'حبر رائقي/جرومي/كزميري/قازان/حبر أبوشخطة'],
        [1606, 'Lutjanus johni', 'Johns snapper', 'نيسرة', 'حبر أبو كية'],
        [1607, 'Lutjanus malabricus', 'Malabar blood snapper', 'حمرة', 'هبر'],
        [1608, 'Lutjanus quinquelineatus', 'Five - line snapper', 'نيسرة', null],
        [1609, 'Lutjanus coeruleolineatus', 'Blueline snapper', null, 'حبر أبو نقطه'],
        [1610, 'Lutjanus ehrenbergi', 'Blackspot snapper', 'نيسرة ابوكية', 'هبره'],
        [1611, 'Lutjanus lutjanus', 'Bigeye snapper', null, 'حبر أبو خط أصفر'],
        [1612, 'Lutjanus russelli', 'Russell\'s snapper', null, 'هباره'],
        [1613, 'Lutjanus sebae', 'Emperor red snapper', null, 'حمير الخلا / حمرة'],
        [1614, 'Macolor niger', 'Black & white snapper', null, 'قطية / قطي / بدعة'],
        [1615, 'Pinjalo pinjalo', 'Pinjalo snapper', 'نعيمي', null],
        [1616, 'Pristipomoides filementosus', 'Crimson jobfish', null, 'دقم ، صرع الشعاب'],
        [1617, 'Pristipomoides multidens', 'Goldbanded jobfish', null, 'أبو سنون ، صرع الباحة'],
        [1618, 'Pristipomoides typus', 'Sharptooth Jobfish', null, 'صرع / صرع أبو سنون حادة'],
        [1619, 'Lutjanidae.nei.', 'Other snappers,Jobfish', 'أنواع أخرى من الحمرة', 'أنواع أخرى من النهاشات'],
        [1701, 'Scolopsis bimaculatus', 'Thumbprint bream', 'سرار / مزميه', null],
        [1702, 'Scolopsis ghanam', 'Dotted bream', 'زراع / مزميه', 'غنم / عيد باحه / قمر'],
        [1703, 'Scolopsis taeniatus', 'Blackstreak bream', 'إبزيمي', null],
        [1704, 'Scolopsis vosmeri', 'Whitecheek bream', 'ينم / حاسيه', null],
        [1705, 'Nemipterus randalli', 'Randall,s threadfin bream', 'باسي', 'مرجان / عندق'],
        [1706, 'Nemipterus japonicus', 'Japanese threadfin bream', 'إبزيمي', 'مرجان'],
        [1707, 'Nemipteridae.nei', null, 'انواع اخرى من الابزيمي', 'انواع اخرى من المرجان'],
        [1801, 'Diagramma pictum', 'Painted sweetlips', 'شخل', null],
        [1802, 'Plectorhinchus gaterinus', 'Blackspotted rubberlip', 'شخل/مطوع/ساردا', 'قطرين/ شطف الطينة / سبيتي'],
        [1803, 'Plectorhinchus pictus', 'Trout sweetlips', 'فرش / سبيطي / مطوع / ينم', 'شيخ/سفط/شعفن'],
        [1804, 'Plectorhinchus schotaf', 'Minstrel sweetlip', 'ينم / جنم', 'شطف / رمص / صدف / تلهام / فتله'],
        [1805, 'Plectorhinchus sordidus', 'Sordid rubberlips', 'فرش', null],
        [1806, 'Pomadasys argenteus', 'Silvery grunt', 'نقرور', 'ناقم'],
        [1807, 'Pomadasy stridens', 'Striped piggy', 'يميم / جمجام', null],
        [1808, 'Haemulidae nei', 'Grunts . nei', 'أنواع أخرى من الشخل', 'أنواع أخرى من القطرين'],
        [1901, 'Gymnocranius grandoculis', 'Blue - lined large eye bream', null, 'شعور ابوعين كبيرة'],
        [1902, 'Lethrinus borbonicus', 'Snubnose emperor', 'يماه', 'شعور برتقالي الزعنفة'],
        [1903, 'Lethrinus microdon', 'Smalltooth emperor', 'شعري / سولي / خرمه', 'شعور جزوي/جحش/شعور كتوبي'],
        [1904, 'Lethrinus harak', 'Blackspot emperor', null, 'شعور أبوكية / شعور محرقي'],
        [1905, 'Lethrinus lentjan', 'Redspot emperor', 'شعري باشخين', 'شعور شركسي/ شعور كريست'],
        [1906, 'Lethrinus mahsena', 'Mahssena', null, 'زعبي / شعور محسني'],
        [1907, 'Lethrinus mahsenoide', 'Redfin emperor', 'جمه', 'محسنه'],
        [1908, 'Lethrinus miniatus', 'Longface emperor', 'شعري سولي', 'شعورأبو زمّر/شعورسولي'],
        [1909, 'Lethrinus nebulosus', 'Spangled emperor', 'شعري /شحدود', 'شعور رمك / خرمي / شحذود/ مركه'],
        [1910, 'Lethrinus ramak', 'Yellowstripe emperor', null, 'شعور أبو صقعة / خشيبي / كتمي/ بنقص/ أبولوز'],
        [1911, 'Lethrinus variegatus', 'Slender emperor', null, 'شعور دربيني ، ورور'],
        [1912, 'Lithrinus xanthochilus', 'Yellowlip emperor', null, 'شعور أبوزهو / خرمية / سولي'],
        [1913, 'Monotaxis grandoculis', 'Bigeye emperor', null, 'شعور أبو عين'],
        [1914, 'Lethrinidae nei.', 'Emperors nei.', 'أنواع أخرى من الشعري', 'أنواع أخرى من الشعور'],
        [2001, 'Acanthopagrus berda', 'Picnic seabream', 'شعم', 'ترسيس/ نزيه/ أعراضي'],
        [2002, 'Acanthopgrus bifasciatus', 'Twobar seabream', 'فسكر/ بنت النوخذه', 'قمر/أم القمر/أبوكحلة/أبوطوقين/بنت النوخذه / رباق'],
        [2003, 'Acanthoparagus latus', 'Yellowfin seabream', 'شعم / أعراضي / قرشوم', 'عريض / مركه (صغير)'],
        [2004, 'Argyrops spinifer', 'King soldierbream', 'عندق / ثور /بياض', 'نجار'],
        [2005, 'Cheimerius nufar', 'Santer seabream', 'نهاش / عرنقش', 'نفر'],
        [2006, 'Crenidens crenidens', 'Karanteen bream', 'بطان', 'حفار / أرسن / نزيه'],
        [2007, 'Diolodus noct', 'Red Sea seabream', 'بطانه / أمجوه / ام مجواة', 'عريض / رعصنه / بطيط'],
        [2008, 'Pagellus affinis', 'Arabian pandora', null, null],
        [2009, 'Rhabdosargus haffara', 'Haffara seabream', 'قرقفان', 'حفار'],
        [2010, 'Rhabdosargus sarba', 'Goldline seabream', 'قرقفان ابوخط ذهبي', 'أبو حجر / مصفر'],
        [2011, 'Sparidentex hasta', 'Sobaity seabream', 'سبيطي (كبير)/امزيزي (صغير)', null],
        [2012, 'Sparidae nei', 'Seabreams nei', 'أنواع أخرى من الشعوم', 'أنواع أخرى من الشعوم'],
        [2101, 'Mulloidichthys flavolineatus', 'Yellowstripe goatfish', 'حامر', 'أبودقن /عنبر / سلطان ابراهيم'],
        [2102, 'Parupeneus forsskali', 'Forsskal\'s goatfish', null, 'سلطان ابراهيم'],
        [2103, 'Upeneus pori', 'Por\'s goatfish', null, 'عنبر'],
        [2104, 'Upeneus tragula', 'Freckled goatfish', null, 'أبودقن'],
        [2105, 'Mullidae nei', 'Goatfishes.nei.', 'حوامر أخرى', 'أنواع أخرى من أبودقن / عنبر'],
        [2201, 'Acanthurus gahhm', 'Black surgeonfish', null, 'قحم'],
        [2202, 'Acanthurus sohal', 'Sohal surgeonfish', null, 'سحل'],
        [2203, 'Ctenochaetus striatus', 'Striated surgeonfish', null, 'سحل حافة الشعب'],
        [2204, 'Naso brevirostris', 'Short-snouted unicornfish', null, 'رهو / رهوان'],
        [2205, 'Naso unicornis', 'Long-snouted unicornfish', null, 'أبو قرن'],
        [2206, 'Zebrasoma veliferum', 'Sailfin tang', null, 'سحل أبوشراع / أبوفليفل / أبوتنباك'],
        [2207, 'Acanthuridae.nei.', 'Unicornfish. nei.', null, 'أنواع أخرى من الأسماك الجراحه و أبوقرن'],
        [2301, 'Myrpristis murdjan', 'Pinecone solderfish', null, 'بصيلي أحمر / تيمس'],
        [2302, 'Neoniphon sammara', 'Sammara squirrelfish', null, 'بصيلي أبيض'],
        [2303, 'Sargocentron diadema', 'Crown squirrels', null, 'أبومزمر / أبو بصيل'],
        [2304, 'Sargocentron spiniferum', 'Sabre sqiurrelfish', null, 'قحاية'],
        [2305, 'Holocentridae nei', 'Sqiurrelfishes.nei.', null, 'أنواع أخرى من الأسماك السنجابية'],
        [2401, 'Bodianus axillaris', 'Axilspot hogfish', null, 'ديك / كناس'],
        [2402, 'Cheilinus undulatus', 'Humphead wrasse', null, 'ترباني/ أبوقري/أبوجبة/ نابليون/مزرطي (صغير)'],
        [2403, 'Choerodon robustus', 'Robust tuskfish', 'جن', null],
        [2404, 'Thalassoma lunare', 'Moon wrasse', 'ميلك', 'أبومليص / أبوخضير'],
        [2405, 'labridae .nei', 'Wrasses n.e.i', null, 'أنواع أخرى من الترباني وأبومليص'],
        [2501, 'Gerres filamentosus', 'Whipfin mojarra', null, 'قاص'],
        [2502, 'Gerres oblongus', 'Slender silverbeddy', 'طراقي / رياش/ بوني', 'أبوعوينه / قاص'],
        [2503, 'Gerres oyena', 'Blacktip mojarra', 'بدح رياش (كبير)/مصلخ (صغير)', 'عوين /رعصن /قاص'],
        [2504, 'Gerreidae nei.', 'Mojarras', 'أنواع أخرى من أسماك البدح', 'أنواع أخرى من أسماك القاص'],
        [2601, 'Bolbometopon muricatus', 'Green humphead parrotfish', 'جن / قين عربي / مزرقان', 'قريان / أبوقري / بوقري'],
        [2602, 'Cetoscarus bicolor', 'Tricolor parrotfish', null, 'حريد أبوحماره/ جمل الحاج/ حديه/ حرديه'],
        [2603, 'Chlorurus gibbus', 'Heavybeak parrotfish', null, 'قيهر'],
        [2604, 'Chlorurus sordidus', 'Daisy parrotfish', 'قين', 'بس/ خضاري/ حريث'],
        [2605, 'Chlorurus strongylocephalus', 'Roundhead parrotfish', null, 'خضاري / حريدة / ديك'],
        [2606, 'Hipposcarus harid', 'Longnose parrotfish', null, 'وليجة /حريد بيضي/ خصي / وريق'],
        [2607, 'Scarus frenatus', 'Bridled parrotfish', null, 'دوالي'],
        [2608, 'Scarus ghobban', 'Blue - barred parrotfish', 'قين فارسي', 'غباني / فرهودي'],
        [2609, 'Scarus niger', 'Dusky parrotfish', 'جن', 'غدري'],
        [2610, 'Scaridae nei', 'Other parrotfishes', 'أنواع أخرى من القين', 'أنواع أخرى من الحريد'],
        [2701, 'Siganus canaliculatus', 'White - spotted spinefoot', 'صافي عربي', null],
        [2702, 'Siganus javus', 'Streaked spinefoot', 'صافي صنيفي', null],
        [2703, 'Siganus rivulatus', 'Marbled spinefoot', 'صافي', 'سيجان'],
        [2704, 'Siganus stellatus', 'Brownspotted spinefoot', null, 'سيجان الباحة / عزب / شبيحة'],
        [2705, 'Siganidae nei.', 'Rabbitfish', 'أنواع أخرى من الصافي', 'أنواع أخرى من السيجان'],
        [2801, 'Balistoides spp.', 'Triggerfish', 'حمارة', 'شعرم جبلي / زهاوي/ أخضر / العبد/ حجم'],
        [2901, 'Platax sp, Ephippus sp.', 'Batfish, Spadefish', 'عماد / خطاف', 'كنف/ أبوجوش'],
        [3001, 'Priacanthus hamrur', 'Moontail bullseye', 'حمره', 'ذيب/حمرور/أبوشرار/ حمري'],
        [3002, 'Priacanthidae nei.', 'Spadefishes, batfishes &scats', 'أنواع أخرى من الحمرور', 'أنواع أخرى من أبوشرار'],
        [3101, 'Centropyge multispinis', 'Dusky angelfish', null, 'أبوبنديرة غزير'],
        [3102, 'pomacanthus asfur', 'Arabian angelfish', null, 'أم عطيه'],
        [3103, 'pomacanthus maculosus', 'Yellowbar angelfish', 'عنفوز', 'قرنقش'],
        [3104, 'Pomacanthidae nei.', 'Angelfishes', 'أنواع أخرى من الأسماك الملائكيه', 'أنواع أخرى من الأسماك الملائكيه'],
        [3201, 'Pelates quadrilinatus', 'Fourlined terapon', null, 'جربوع'],
        [3202, 'Terapon jarbua', 'Jarbua terapoon', 'زمرور', 'جربوع'],
        [3203, 'Terapon puta', 'Spinycheek terapon', null, 'جربوع نحيف'],
        [3204, 'Terapon theraps', 'Largescale terapon', null, 'شخرم'],
        [3301, 'Ablennes hians', 'Flat needlefish', 'سلس', null],
        [3302, 'Tylosurus choram', 'Red Sea houndfish', null, 'خرم'],
        [3303, 'Tylosurus crocodilus crocodilus', 'Hound needlefish', 'حاقول', 'أبوشري/أبومخيط/مسيف/خرم/خرم طوري/درادي'],
        [3304, 'Belonidae nei.', 'Needlefishes', 'أنواع أخرى من أسماك الحاقول', 'أنواع أخرى من أسماك الخرم'],
        [3401, 'Sphyraena barracuda', 'Great barracuda', 'جد', 'عقام / براكودا'],
        [3402, 'Sphyraena flavicauda', 'Yellowtail barracuda', null, 'صهب'],
        [3403, 'Sphyraena forsteri', 'Bigeye barracuda', null, 'كنايا / توداف أحمر'],
        [3404, 'Sphyraena jello', 'Pickhandle barracuda', 'جد / إدويلمي', 'كنايا / توداف أسود / عقام'],
        [3405, 'Sphyraena obtusata', 'Obtuse barracuda', 'ادويلمي/ جد', 'زرقان'],
        [3406, 'Sphyraenidae nei', 'Barracudas', 'أنواع أخرى من الجد', 'أنواع أخرى من البركودا'],
        [3501, 'Crenidens crenidens', 'Fringelip mullet', null, 'عربي'],
        [3502, 'Liza subviridis', 'Greenback mullet', 'بياح / جاحا', 'عربي'],
        [3503, 'Oedalechilus labiosus', 'Hornlip mullet', null, 'جيلان'],
        [3504, 'Valamugil seheli', 'Bluespot mullet', 'بياح (كبير) / ميد (صغير)', 'عربي'],
        [3505, 'Mugilidae nei.', 'Other Mullet', 'أنواع أخرى من أسماك البياح', 'أنواع أخرى من أسماك العربي'],
        [3601, 'Rachycentron canadum', 'Cobia', 'سكن', 'قميري/كمل نقر/كمل / خوت / سخلة'],
        [3701, 'Caesio lunaris', 'Lunar fusilier', 'خطاف', 'واغش / سمسور'],
        [3702, 'Caesio suevica', 'Suez fusilier', null, 'عيده / تمير'],
        [3703, 'Caesio varilineata', 'Variable - lined fusilier', 'ديايوة/ خضيم', 'قمير'],
        [3704, 'Caesionidae nei', 'Other fusilier', 'أنواع أخرى من الديايوة', 'أنواع أخرى من أسماك العيده'],
        [3801, 'Arothorn stellatus', 'Starry toadfish', 'فقل / عنزه', 'درمه'],
        [3802, 'Lagocephalus lunaris', 'Green rough - back puffer', 'فقل', 'درمه خضراء'],
        [3803, 'Lagocephalus sceleratus', 'Silverstrip blaasop', null, 'قراض'],
        [3804, 'Tetraodontidae nei.', null, 'أنواع أخرى من الفقل', 'أنواع أخرى من اأسماك الدرمه'],
        [3901, 'Alectis indicus', 'Indian threadfish', 'حمام / كراري / بنقالة/ خيط / عثيمي', 'ضيم / هطل / شاويش/ بياض أبو تيس/ أبو طبق'],
        [3902, 'Alepes djeddaba', 'Shrimp scad', 'جنيس / تراف', 'جدبة'],
        [3903, 'Atule mate', 'Yellowtail scad', 'جنيس', 'بياضه'],
        [3904, 'Carangoides bajad', 'Orangespotted trevally', 'حمام جش', 'بياض قز'],
        [3905, 'Carangoides ferdau', 'Blue trevally', 'كراري', 'فردوه/ ضيمه'],
        [3906, 'Carangoides fulvoguttatus', 'Yellowspotted trevally', 'حمام سليخ', 'بياض سليخة'],
        [3907, 'Carangoides malabricus', 'Malabar trevally', 'حمام', 'نسخة /بياض بكاس'],
        [3908, 'Caranx bifasciatus', 'Dusky Jack', 'كفدار', null],
        [3909, 'Caranx ignobilis', 'Giant trevally', 'حمام', 'بياض قرب/قرمع/جرم/قضم'],
        [3910, 'Caranx melampygus', 'Bluefin trevally', null, 'بياض كسر / بياض قصر'],
        [3911, 'Caranx sexfasciatus', 'Bigeye trevally', 'حمام', 'فردوه / جدرة / لعيلع / بياض أبو عين'],
        [3912, 'Decapterus russelli', 'Indian scad', 'خضرة', 'شدبة / بوال'],
        [3913, 'Elagatis bipinnulata', 'Rainbow runner', null, 'قلم العمدة / غريب / مسلبة'],
        [3914, 'Gnathanodon speciosus', 'Golden trevally', 'ربيب', 'نسخ / بكاس / ضوف / بياض عريجاء'],
        [3915, 'Megalaspis cordyla', 'Torpedo scad', 'جدج/ تيتي/ ظلعه', 'بياض طرفه/ خرطوم'],
        [3916, 'Naucrates ductor', 'Pilotfish', 'حمام عربي / دبس', null],
        [3917, 'Parastromateus niger', 'Black pomfret', 'حلوايوه', 'زبيدي أسود'],
        [3918, 'Scomberoides commersonnianus', 'Talang queenfish', 'لحلاح', 'خرج (ص) /طلعاني / بسار/ليحلاح/غزلان/دورب/شروي/ لسنه'],
        [3919, 'Scomberoides lysan', 'Doublespotted queenfish', 'ضلعة', 'عبري/ توداف / شروي'],
        [3920, 'Scomberoides tol', 'Needlescaled queenfish', 'ضلعة / بسار', 'لسن/ ظبي / درب'],
        [3921, 'Selar crumenophthalmus', 'Bigeye scad', 'دردمان/ بالج', null],
        [3922, 'Seriolina nigrofasciata', 'Blackbanded trevally', 'دبس/ حمام عربي', null],
        [3923, 'Trachinotus blochii', 'Snubnose pompano', 'طلاح / بوصلبوخ / سبن / طلاح', 'بياض ضيم'],
        [3924, 'Carangidae nei', 'Jacks, Trevallies n.e.i.', 'أنواع أخرى من الحمام', 'أنواع أخرى من البياض'],
        [4001, 'Pampus argenteus', 'Silver pomfret', 'زبيدي ابيض', null],
        [5001, 'Amblygaster sirm', 'Spotted sardinella', 'عوم', 'سردين الباحة'],
        [5002, 'Dussumieria elopsoides', 'Slender rainbow sardin', null, 'سردين طويل'],
        [5003, 'Nematalosa nasus', 'Bloch\'s gizzard shad', 'شروم / جواف', 'سردين'],
        [5004, 'Sardinella gibbosa', 'Goldstripe sardinella', 'عوم', 'سردين'],
        [5005, 'Clupeidae nei', 'Sardines.nei.', 'أنواع أخرى من الشروم', 'انواع اخرى من السردين'],
        [5101, 'Euthynnus affinis', 'Kawakawa', 'تبان', 'معقب/ أبودوم /شيروي'],
        [5102, 'Gymnosarda unicolor', 'Dogtooth tuna', null, 'ثمد'],
        [5103, 'Rastrelliger kanagurta', 'Indian mackerel', 'كرفة', 'باغة'],
        [5104, 'Scomberomorus commerson', 'Narrow - barred Spanish mackerel', 'كنعد كبير / كنعد صغير', 'دراك (كبير) / ضرس (صغير)'],
        [5105, 'Scomberomorus guttatus', 'Indoــpacific king mackerel', 'خباط', 'صويح'],
        [5106, 'Thunnus tanggol', 'Longtail tuna', 'تبان طويل الذيل', 'زينوب /تونة/ شك الزور'],
        [5107, 'Scombridae nei', 'Other tunas and makerels', 'أنواع أخرى من الكنعد والتونا', 'أنواع أخرى من الدراك والتونا والباغة'],
        [5201, 'Istiophorus platypterus', 'Indo - Pacific sailfish', 'فرس', 'فرس البحر / أبوشراع'],
        [5301, 'Kyphosus cinerascens', 'Blue seachub', null, 'تهمل'],
        [5302, 'Kyphosidae nei.', 'Other sea chubs', null, 'أنواع أخرى من أسماك التهمل'],
        [5401, 'Grammoplites suppositus', 'Spotfin flathead', 'وحر', 'رقاد'],
        [5402, 'Cociella crocodiles', 'Crocodile flathead', null, 'رقده'],
        [5403, 'Rogadius prionotus', 'Blackbloch flathead', null, 'رقده'],
        [5404, 'Platycephalidae nei.', 'Other Flatheads', 'أنواع أخرى من الوحره', 'أنواع أخرى من أسماك الرقاد'],
        [5501, 'Carcharhinus melanopterus', 'Blacktip reef shark', 'جرجور ابوريشة سوداء', 'قرش ابو ريشة سوداء / نوفاري / عرص / بطاني'],
        [5502, 'Galeocerdo cuvieri', 'Tiger shark', null, 'قرش نمراني / قصف'],
        [5503, 'Loxodon macrorhinus', 'Sliteye shark', null, 'قرش'],
        [5504, 'Carcharhinidae nei.', 'Other requiem sharks', 'انواع اخرى من الجرجور', 'انواع اخرى من القروش'],
        [5601, 'Himantura gerrardi', 'Sharpnose stingray', 'لخمة', 'رقيطة'],
        [5602, 'Himantura uarnak', 'Honeycomb stingray', 'لخمة', 'رقيطة / ورنك'],
        [5603, 'Pastinachus sephen', 'Cowtail stingray', 'بيجي', 'سفن'],
        [5604, 'Taeniura lymma', 'Bluespotted ribbontail ray', null, 'لمه'],
        [5605, 'Dasyatidae nei', 'Rays . nei.', 'انواع اخرى من اللخم', 'انواع اخرى من الرقيطات'],
        [5701, 'Fenneropenaeus indicus', 'Indian white shrimp', null, 'الهندي الأبيض'],
        [5702, 'Marsupenaeus japonicus', 'Kurume shrimp', 'النمر العنابي', 'الربيان الياباني'],
        [5703, 'Metapenaeus affinis', null, 'ربيان شحامية', null],
        [5704, 'Metapenaeus monoceros', 'Speckled shrimp', 'الربيان الخشن', 'ربيان شحامية / دكر / ربيان خشن'],
        [5705, 'Penaeus latisulcatus', 'Western king prawn', null, null],
        [5706, 'Penaeus monodon', 'Giant tiger prawn', null, 'الجمبري النمراني العملاق'],
        [5707, 'Penaeus semisulcatus', 'Green tiger prawn', 'ربيان أم نعيرة', 'جمبري مخلط'],
        [5708, 'Trachypenaeus curvirostris', 'Southern rough shrimp', null, null],
        [5709, 'Penaeid spp.nei.', 'Shrimps .nei.', 'انواع اخرى من الربيان', 'انواع اخرى من الجمبري'],
        [5801, 'Portunus pelagicus', 'Blue swimming crab', 'قبقب', 'كبوريا / أبو مقص / مصنبي'],
        [5802, 'Portunidae nei', 'Crab . nei', 'انواع اخرى من القبقب', 'أنواع أخرى من أبو مقص'],
        [5803, 'Palinuridae', 'Spiny lobster', null, 'استاكوزا'],
        [5804, 'Panulirus penicillatus', 'Pronghorn spiny lobster', null, 'استاكوزا'],
        [5805, 'Panulirus versicolor', 'Painted spiny lobster', null, 'استاكوزا'],
        [5806, 'Scyllaridae', 'Slipper lobster', 'أم الربيان ثلاثي النقط', 'أم الربيان'],
        [5807, 'Thuenus orientalis', 'Flathead lobster', 'أم الربيان', 'أم الربيان'],
        [5901, 'Uroteuthis (Photololigo) edulis', 'Swordtip squid', 'خثاق', 'حبار أحمر / سبيدج'],
        [5902, 'Sepia pharaonis', 'Pharaoh cuttlefish', 'حبارة / خثاق ابيض', 'حبارأبيض'],
        [5903, 'Sepiella inermis', 'Spineless cuttlefish', null, 'نوع أخر من الحبار الأبيض'],
        [6001, 'Octopus aegina', 'Sandbird octopus', null, 'أخطبوط'],
        [6101, 'Gazza minuta', 'Toothpony', null, 'أبو قرص'],
        [6102, 'Leiognathus bindus', 'Orangefin ponyfish', 'تراجي', 'أبو قرص'],
        [6103, 'Leiognathus fasciatus', 'Barred ponyfish', null, 'أبو قرص'],
        [6104, 'Leiognathus leuciscus', 'Whipfin ponyfish', null, 'أبو قرص'],
        [6105, 'Leiognathus oblongus', 'Oblong ponyfish', null, 'أبو قرص'],
        [6106, 'Secutor insidiator', 'Pugnose ponyfish', null, 'أبو قرص'],
        [6107, 'Leiognathidae nei.', 'Other ponyfish', 'أنواع أخرى من أسماك التراجي', 'أنواع أخرى من أبوقرص'],
        [6201, 'Psettodes erumi', 'Indian spiny turbot', 'خوفعه', 'سمك موسى'],
        [6301, 'Sillago sihama', 'Sulver sillago', 'حاسوم', 'شحاميه'],
        [6302, 'Sillaginidae nei.', 'Other sillago', 'أنواع أخرى من الحاسوم', 'أنواع أخرى من أسماك الشحاميه'],
        [6401, 'Albula glossodonta', 'Roundjaw bonefish', null, 'وعثة / بنك'],
    ];

    /**
     * The sheet is the authority on a coded species, so every run writes its names back.
     * Species added by hand at the desk carry no code and are left alone.
     */
    public function run(): void
    {
        $families = FishFamily::query()->pluck('id', 'code');

        collect(self::SPECIES)
            ->map(fn (array $species): array => [
                'code' => $species[0],
                'fish_family_id' => $families->get(intdiv($species[0], 100) * 100),
                'name_ar' => $this->displayName($species[3], $species[4], $species[1]),
                'scientific_name' => $species[1],
                'english_name' => $species[2],
                'local_name_gulf' => $species[3],
                'local_name_red_sea' => $species[4],
                'sort_order' => $species[0],
            ])
            ->chunk(100)
            ->each(fn (Collection $chunk) => FishSpecies::query()->upsert($chunk->values()->all(), ['code'], [
                'fish_family_id',
                'name_ar',
                'scientific_name',
                'english_name',
                'local_name_gulf',
                'local_name_red_sea',
                'sort_order',
            ]));
    }

    /**
     * The sheet lists every alias a species goes by, separated by slashes or commas.
     * Dashboards and reports print one name, so the first alias becomes the short name —
     * the Gulf one where the sheet records it, otherwise the Red Sea one.
     */
    private function displayName(?string $gulfName, ?string $redSeaName, string $scientificName): string
    {
        $name = $gulfName ?? $redSeaName;

        if ($name === null) {
            return $scientificName;
        }

        return trim(explode('/', str_replace('،', '/', $name))[0]);
    }
}
