@extends('layouts.dashboard')

@section('title', 'ملفي الوظيفي')
@section('body-class', 'employment-profile-page')

@section('content')
@if(!$employee)
    <section class="panel employment-profile-empty"><div class="employment-empty-mark">!</div><div><h2>ملفك الوظيفي قيد التجهيز</h2><p>مرحبًا {{ $account->full_name }}. تم تفعيل الحساب، لكن لم يكتمل ربطه بسجل الموظف بعد.</p><p class="panel-hint">تواصل مع الموارد البشرية لاستكمال بيانات التعيين.</p></div></section>
@else
@php($job = $application?->job)
@php($displayName = $application?->full_name ?: $account->full_name)
@php($jobTitle = $employee->jobTitle?->name ?: ($job?->title_ar ?? 'موظف'))
@php($department = $employee->department?->name ?: ($job?->department ?? '—'))
<div class="employment-profile-shell">
    <section class="panel employment-profile-hero"><div class="employment-profile-avatar">{{ mb_substr($displayName, 0, 1) }}</div><div class="employment-profile-identity"><div class="employment-profile-eyebrow">بوابة الموظف الذاتية</div><h1>{{ $displayName }}</h1><p>{{ $jobTitle }} · {{ $department }}</p><div class="employment-profile-tags"><span class="badge">{{ config("employment.employee_statuses.{$employee->status}", $employee->status) }}</span>@if($employee->employee_number)<span class="employment-reference" dir="ltr">#{{ $employee->employee_number }}</span>@endif</div></div><dl class="employment-hero-facts"><div><dt>ميناء اليوم</dt><dd>{{ $assignment?->port?->name ?? $employee->port?->name ?? 'غير محدد' }}</dd></div><div><dt>تاريخ التعيين</dt><dd>{{ $employee->hire_date?->format('Y/m/d') ?? '—' }}</dd></div><div><dt>نوع العقد</dt><dd>{{ config("employment.contract_types.{$employee->activeContract?->contract_type}", '—') }}</dd></div><div><dt>القسم</dt><dd>{{ $department }}</dd></div></dl></section>
    <div class="employment-profile-layout"><main class="employment-profile-main">
        <section class="panel employment-profile-section"><div class="employment-section-heading"><div><span>01</span><h2>الهوية وبيانات التواصل</h2></div><p>بياناتك المعتمدة</p></div><dl class="employment-data-grid"><div><dt>الاسم الكامل</dt><dd>{{ $displayName }}</dd></div><div><dt>نوع الهوية</dt><dd>{{ config("employment.identity_types.{$application?->identity_type}", '—') }}</dd></div><div><dt>رقم الهوية</dt><dd dir="ltr">{{ $application?->identity_number ?: ($employee->national_id ?: '—') }}</dd></div><div><dt>الجنسية</dt><dd>{{ config("employment.nationalities.{$application?->nationality}", '—') }}</dd></div><div><dt>الجوال</dt><dd dir="ltr">{{ $application?->mobile ?? '—' }}</dd></div><div><dt>البريد</dt><dd dir="ltr">{{ $application?->email ?: ($account->email ?? '—') }}</dd></div><div><dt>المدينة</dt><dd>{{ $application?->city ?? '—' }}</dd></div><div class="employment-data-wide"><dt>العنوان</dt><dd>{{ $application?->address ?? '—' }}</dd></div></dl></section>
        <section class="panel employment-profile-section"><div class="employment-section-heading"><div><span>02</span><h2>الوظيفة وموقع العمل</h2></div><p>التعيين الحالي</p></div><dl class="employment-data-grid"><div><dt>رقم الموظف</dt><dd dir="ltr">{{ $employee->employee_number ?? '—' }}</dd></div><div><dt>المسمى</dt><dd>{{ $jobTitle }}</dd></div><div><dt>القسم</dt><dd>{{ $department }}</dd></div><div><dt>الميناء</dt><dd>{{ $assignment?->port?->name ?? $employee->port?->name ?? $application?->preferredPort?->name ?? $job?->port?->name ?? '—' }}</dd></div><div><dt>المناوبة</dt><dd>{{ $assignment?->shift?->name ?? '—' }}</dd></div><div><dt>وقت المناوبة</dt><dd dir="ltr">{{ $assignment ? $assignment->shift->start_time.'—'.$assignment->shift->end_time : '—' }}</dd></div><div><dt>المدير المباشر</dt><dd>{{ $employee->manager?->user?->full_name ?? '—' }}</dd></div><div><dt>رقم العقد</dt><dd dir="ltr">{{ $employee->activeContract?->contract_number ?? '—' }}</dd></div><div><dt>نهاية العقد</dt><dd>{{ $employee->activeContract?->end_date?->format('Y/m/d') ?? '—' }}</dd></div></dl></section>
        <section class="panel employment-profile-section"><div class="employment-section-heading"><div><span>03</span><h2>الحضور هذا الشهر</h2></div><p>{{ config("payroll.months.".today()->month) }} {{ today()->year }}</p></div><div class="kpi-grid employment-attendance-kpis"><div class="kpi-card"><span class="stat-label">أيام مسجلة</span><span class="stat-value">{{ $attendanceSummary->recorded_days ?? 0 }}</span></div><div class="kpi-card"><span class="stat-label">حضور</span><span class="stat-value">{{ $attendanceSummary->present_days ?? 0 }}</span></div><div class="kpi-card warn-tone"><span class="stat-label">تأخير</span><span class="stat-value">{{ $attendanceSummary->late_days ?? 0 }}</span></div><div class="kpi-card alert-tone"><span class="stat-label">غياب</span><span class="stat-value">{{ $attendanceSummary->absent_days ?? 0 }}</span></div></div><div class="table-responsive"><table><thead><tr><th>التاريخ</th><th>المناوبة</th><th>الحالة</th><th>الحضور</th><th>الانصراف</th></tr></thead><tbody>@forelse($recentAttendance as $attendance)<tr><td>{{ $attendance->attendance_date->format('Y/m/d') }}</td><td>{{ $attendance->shift->name }}</td><td>{{ config("employment.attendance_statuses.{$attendance->status}") }}</td><td dir="ltr">{{ $attendance->check_in?->format('H:i') ?? '—' }}</td><td dir="ltr">{{ $attendance->check_out?->format('H:i') ?? '—' }}</td></tr>@empty<tr><td colspan="5">لا توجد سجلات حضور.</td></tr>@endforelse</tbody></table></div></section>
        <section class="panel employment-profile-section"><div class="employment-section-heading employment-section-heading-action"><div><span>04</span><h2>الإجازات</h2></div><details class="employment-leave-request"><summary class="btn btn-primary btn-sm">طلب إجازة</summary><form method="post" action="{{ route('dashboard.profile.leaves.store') }}" class="employment-leave-form">@csrf<div class="form-group"><label>من</label><input type="date" name="start_date" min="{{ today()->toDateString() }}" required></div><div class="form-group"><label>إلى</label><input type="date" name="end_date" min="{{ today()->toDateString() }}" required></div><div class="form-group employment-form-wide"><label>السبب</label><textarea name="reason" maxlength="255" rows="3"></textarea></div><button class="btn btn-primary" type="submit">إرسال الطلب</button></form></details></div><table><thead><tr><th>الفترة</th><th>السبب</th><th>الحالة</th><th>التقديم</th></tr></thead><tbody>@forelse($leaveHistory as $leave)<tr><td>{{ $leave->start_date->format('Y/m/d') }} — {{ $leave->end_date->format('Y/m/d') }}</td><td>{{ $leave->reason ?? '—' }}</td><td>{{ config("employment.leave_statuses.{$leave->status}") }}</td><td>{{ $leave->created_at?->format('Y/m/d') }}</td></tr>@empty<tr><td colspan="4">لا توجد طلبات إجازة.</td></tr>@endforelse</tbody></table></section>
        <section class="panel employment-profile-section"><div class="employment-section-heading"><div><span>05</span><h2>تاريخ الرواتب</h2></div></div><div class="table-responsive"><table><thead><tr><th>الفترة</th><th>الاستحقاقات</th><th>الخصومات</th><th>الصافي</th><th></th></tr></thead><tbody>@forelse($payrollHistory as $snapshot)<tr><td>{{ config("payroll.months.{$snapshot->payrollRun->period_month}") }} {{ $snapshot->payrollRun->period_year }}</td><td>{{ number_format((float) $snapshot->total_earnings, 2) }}</td><td class="employment-negative">{{ number_format((float) $snapshot->total_deductions, 2) }}</td><td><strong>{{ number_format((float) $snapshot->net_salary, 2) }} ر.س</strong></td><td><a class="btn btn-outline btn-sm" href="{{ route('dashboard.payslips.show', $snapshot) }}">كشف الراتب</a></td></tr>@empty<tr><td colspan="5">لم يصدر مسير راتب بعد.</td></tr>@endforelse</tbody></table></div></section>
    </main><aside class="employment-profile-aside">
        <section class="panel employment-profile-section"><div class="employment-section-heading employment-section-heading-compact"><div><span>06</span><h2>آخر راتب</h2></div></div>@if($latestPayroll)<p class="employment-period">{{ config("payroll.months.{$latestPayroll->payrollRun->period_month}") }} {{ $latestPayroll->payrollRun->period_year }}</p><dl class="employment-money-list"><div><dt>الأساسي</dt><dd>{{ number_format((float) $latestPayroll->basic_salary, 2) }}</dd></div><div><dt>الاستحقاقات</dt><dd>{{ number_format((float) $latestPayroll->total_earnings, 2) }}</dd></div><div><dt>الخصومات</dt><dd class="employment-negative">{{ number_format((float) $latestPayroll->total_deductions, 2) }}</dd></div><div class="employment-money-total"><dt>الصافي</dt><dd>{{ number_format((float) $latestPayroll->net_salary, 2) }} ر.س</dd></div></dl><a class="btn btn-primary" href="{{ route('dashboard.payslips.show', $latestPayroll) }}">عرض كشف الراتب</a>@else<div class="employment-salary-empty"><p>لم يصدر مسير راتب بعد.</p></div>@endif</section>
        <section class="panel employment-profile-section"><div class="employment-section-heading employment-section-heading-compact"><div><span>06</span><h2>ملف التوظيف</h2></div></div><dl class="employment-data-stack"><div><dt>رقم الطلب</dt><dd dir="ltr">{{ $application?->reference_no ?? '—' }}</dd></div><div><dt>الوظيفة</dt><dd>{{ $job?->title_ar ?? '—' }}</dd></div><div><dt>حالة الطلب</dt><dd>{{ config("employment.application_statuses.{$application?->status}", '—') }}</dd></div><div><dt>التقديم</dt><dd>{{ $application?->submitted_at?->format('Y/m/d') ?? '—' }}</dd></div></dl></section>
        <section class="panel employment-profile-section"><div class="employment-section-heading employment-section-heading-compact"><div><span>07</span><h2>المؤهلات</h2></div></div><dl class="employment-data-stack"><div><dt>المؤهل</dt><dd>{{ config("employment.education_levels.{$application?->education_level}", '—') }}</dd></div><div><dt>التخصص</dt><dd>{{ $application?->specialization ?? '—' }}</dd></div><div><dt>الخبرة</dt><dd>{{ $application?->experience_years ?? 0 }} سنة</dd></div></dl>@if($application?->skills)<div class="employment-profile-copy"><h3>المهارات</h3><p>{{ $application->skills }}</p></div>@endif</section>
    </aside></div>
</div>
@endif
@endsection
