@extends('layouts.dashboard')

@section('title', 'القوارب والرحلات')

@section('content')
<div class="employment-admin-shell">
    <section class="employment-admin-hero"><div><span class="employment-eyebrow">المتابعة التشغيلية</span><h2>القوارب والرحلات</h2><p>عرض الرحلات ضمن نطاق صلاحيات المستخدم ومتابعة تقدمها من الوصول إلى الإغلاق.</p></div>@if(auth()->user()->role->code === 'super_admin')<a class="btn btn-primary" href="{{ route('dashboard.trips.create') }}">إضافة رحلة</a>@endif</section>
    <form method="get" class="panel employment-filter-bar"><label>من تاريخ<input type="date" name="date_from" value="{{ $filters['date_from'] }}"></label><label>إلى تاريخ<input type="date" name="date_to" value="{{ $filters['date_to'] }}"></label><label>الحالة<select name="status"><option value="">كل الحالات</option>@foreach(config('trips.statuses') as $value => $label)<option value="{{ $value }}" @selected(($filters['status'] ?? null) === $value)>{{ $label }}</option>@endforeach</select></label>@if($ports->isNotEmpty())<label>الميناء<select name="port_id"><option value="">كل الموانئ</option>@foreach($ports as $port)<option value="{{ $port->id }}" @selected((string) ($filters['port_id'] ?? '') === (string) $port->id)>{{ $port->name }}</option>@endforeach</select></label>@endif<button class="btn btn-primary" type="submit">تطبيق</button></form>
    <section class="employment-kpis"><article><span>في الطريق</span><strong>{{ $stats->expected_count }}</strong></article><article><span>وصلت</span><strong>{{ $stats->arrived_count }}</strong></article><article><span>بانتظار موظف</span><strong>{{ $stats->waiting_count }}</strong></article><article><span>تحت الإحصاء</span><strong>{{ $stats->counting_count }}</strong></article><article><span>بانتظار مراجعة</span><strong>{{ $stats->pending_count }}</strong></article><article><span>معتمدة</span><strong>{{ $stats->approved_count }}</strong></article><article><span>مغلقة</span><strong>{{ $stats->closed_count }}</strong></article><article><span>متوسط الإحصاء</span><strong>{{ $stats->average_count_minutes !== null ? round($stats->average_count_minutes) : '—' }}</strong></article></section>
    <section class="panel employment-list-panel"><header class="employment-section-heading"><div><span>المتابعة المباشرة</span><h3>جدول الرحلات</h3></div><small>{{ $trips->total() }} رحلة</small></header>
        @if($trips->isEmpty())<div class="employment-empty-state"><strong>لا توجد رحلات مطابقة</strong><p>غيّر المدى الزمني أو الفلاتر.</p></div>@else<div class="employment-table-wrap"><table class="employment-applications-table"><thead><tr><th>الرحلة</th><th>الميناء</th><th>القارب والكابتن</th><th>الوصول</th><th>الموظف</th><th>الحالة</th><th>الأوزان</th><th>الإجراءات</th></tr></thead><tbody>
        @foreach($trips as $trip)<tr><td><strong dir="ltr">{{ $trip->trip_code }}</strong></td><td>{{ $trip->port->name }}</td><td><strong>{{ $trip->boat->name }}</strong><small>{{ $trip->captain->full_name }}</small></td><td><small>متوقع: {{ $trip->expected_arrival?->format('Y-m-d H:i') ?? '—' }}</small><small>فعلي: {{ $trip->actual_arrival?->format('Y-m-d H:i') ?? '—' }}</small></td><td>{{ $trip->assignedEmployee?->user?->full_name ?? '—' }}</td><td><span class="badge">{{ config("trips.statuses.{$trip->status}") }}</span></td><td><small>مبلغ: {{ $trip->captain_reported_weight ?? '—' }}</small><small>فعلي: {{ $trip->verified_weight ?? '—' }}</small></td><td>@if(auth()->user()->role->code === 'super_admin')<div class="employment-row-actions">@if($trip->status === 'expected')<form method="post" action="{{ route('dashboard.trips.arrive', $trip) }}">@csrf @method('PATCH')<button class="btn btn-outline btn-sm" type="submit">تسجيل الوصول</button></form>@endif<form method="post" action="{{ route('dashboard.trips.destroy', $trip) }}" data-confirm="هل تريد حذف الرحلة؟"><input type="hidden" name="_token" value="{{ csrf_token() }}">@method('DELETE')<button class="btn btn-outline btn-sm" type="submit">حذف</button></form></div>@else—@endif</td></tr>@endforeach
        </tbody></table></div>{{ $trips->links() }}@endif
    </section>
</div>
@endsection
