@extends('layouts.dashboard')

@section('title', 'الفروقات وجودة البيانات')

@section('content')
<div class="employment-admin-shell">
    <section class="employment-admin-hero"><div><span class="employment-eyebrow">مراقبة الجودة</span><h2>الفروقات وجودة البيانات</h2><p>تحليل الاختلاف بين بلاغات الكباتن والوزن المتحقق، واعتماد الرحلات المعلقة.</p></div></section>
    <form method="get" class="panel employment-filter-bar"><label>من تاريخ<input type="date" name="date_from" value="{{ $filters['date_from'] }}"></label><label>إلى تاريخ<input type="date" name="date_to" value="{{ $filters['date_to'] }}"></label>@if($ports->count() > 1)<label>الميناء<select name="port_id"><option value="">كل الموانئ</option>@foreach($ports as $port)<option value="{{ $port->id }}" @selected((string) ($filters['port_id'] ?? '') === (string) $port->id)>{{ $port->name }}</option>@endforeach</select></label>@endif<button class="btn btn-primary" type="submit">تطبيق الفلاتر</button></form>
    <section class="employment-kpis"><article><span>رحلات ذات فروقات</span><strong>{{ $stats->total_trips ?? 0 }}</strong></article><article><span>فروقات بسيطة</span><strong>{{ $stats->minor_count ?? 0 }}</strong></article><article><span>فروقات متوسطة</span><strong>{{ $stats->medium_count ?? 0 }}</strong></article><article><span>فروقات كبيرة</span><strong>{{ $stats->major_count ?? 0 }}</strong></article><article><span>أصناف غير مبلغة</span><strong>{{ $unreportedCount }}</strong></article><article><span>متوسط الفرق</span><strong>{{ number_format((float) ($stats->average_percent ?? 0), 1) }}%</strong></article><article><span>إجمالي فرق الوزن</span><strong>{{ number_format((float) ($stats->total_kg ?? 0), 1) }}</strong></article><article><span>بانتظار المراجعة</span><strong>{{ $stats->pending_count ?? 0 }}</strong></article></section>

    <div class="grid-3">
        <section class="panel"><h3>أعلى القوارب في الفروقات</h3><table><thead><tr><th>القارب</th><th>الرحلات</th><th>متوسط الفرق</th></tr></thead><tbody>@forelse($topBoats as $row)<tr><td>{{ $row->boat_name }}</td><td>{{ $row->trips_count }}</td><td>{{ number_format((float) $row->average_diff, 1) }}%</td></tr>@empty<tr><td colspan="3">لا توجد بيانات.</td></tr>@endforelse</tbody></table></section>
        <section class="panel"><h3>أعلى الكباتن في الفروقات</h3><table><thead><tr><th>الكابتن</th><th>الرحلات</th><th>متوسط الفرق</th></tr></thead><tbody>@forelse($topCaptains as $row)<tr><td>{{ $row->captain_name }}</td><td>{{ $row->trips_count }}</td><td>{{ number_format((float) $row->average_diff, 1) }}%</td></tr>@empty<tr><td colspan="3">لا توجد بيانات.</td></tr>@endforelse</tbody></table></section>
        <section class="panel"><h3>أنواع السمك الأكثر اختلافًا</h3><table><thead><tr><th>النوع</th><th>فرق الوزن</th></tr></thead><tbody>@forelse($topSpecies as $row)<tr><td>{{ $row->name_ar }}</td><td>{{ number_format((float) $row->diff_kg, 1) }} كجم</td></tr>@empty<tr><td colspan="2">لا توجد بيانات.</td></tr>@endforelse</tbody></table></section>
    </div>
    <div class="grid-3">
        <section class="panel"><h3>أسباب الفروقات</h3><table><thead><tr><th>السبب</th><th>التكرار</th></tr></thead><tbody>@forelse($topReasons as $row)<tr><td>{{ $row->reason }}</td><td>{{ $row->total }}</td></tr>@empty<tr><td colspan="2">لا توجد بيانات.</td></tr>@endforelse</tbody></table></section>
        <section class="panel"><h3>الفروقات حسب الميناء</h3><table><thead><tr><th>الميناء</th><th>الرحلات</th></tr></thead><tbody>@forelse($byPort as $row)<tr><td>{{ $row->port_name }}</td><td>{{ $row->trips_count }}</td></tr>@empty<tr><td colspan="2">لا توجد بيانات.</td></tr>@endforelse</tbody></table></section>
        <section class="panel"><h3>الفروقات حسب الموظف</h3><table><thead><tr><th>الموظف</th><th>الرحلات</th><th>متوسط الفرق</th></tr></thead><tbody>@forelse($byEmployee as $row)<tr><td>{{ $row->employee_name ?? 'غير مسند' }}</td><td>{{ $row->trips_count }}</td><td>{{ number_format((float) $row->average_diff, 1) }}%</td></tr>@empty<tr><td colspan="3">لا توجد بيانات.</td></tr>@endforelse</tbody></table></section>
    </div>
    <section class="panel employment-list-panel"><header class="employment-section-heading"><div><span>طابور الاعتماد</span><h3>الفروقات المعلقة</h3></div><small>{{ $pendingDiscrepancies->count() }} سجل</small></header><div class="employment-table-wrap"><table class="employment-applications-table"><thead><tr><th>الرحلة</th><th>الميناء</th><th>القارب</th><th>الفرق</th><th>النسبة</th><th>التصنيف</th><th>السبب</th><th>الإجراء</th></tr></thead><tbody>
        @forelse($pendingDiscrepancies as $discrepancy)<tr><td><strong dir="ltr">{{ $discrepancy->trip->trip_code }}</strong></td><td>{{ $discrepancy->trip->port->name }}</td><td>{{ $discrepancy->trip->boat->name }}</td><td>{{ $discrepancy->diff_kg }} كجم</td><td>{{ $discrepancy->diff_percent }}%</td><td><span class="badge">{{ config("discrepancies.severity.{$discrepancy->severity}") }}</span></td><td>{{ $discrepancy->reason ?? '—' }}</td><td><form method="post" action="{{ route('dashboard.discrepancies.approve', $discrepancy) }}" data-confirm="تأكيد اعتماد هذا الفرق والرحلة؟">@csrf @method('PATCH')<button class="btn btn-primary btn-sm" type="submit">اعتماد</button></form></td></tr>@empty<tr><td colspan="8">لا توجد فروقات بانتظار الاعتماد.</td></tr>@endforelse
        </tbody></table></div></section>
</div>
@endsection
