@extends('layouts.dashboard')

@section('title', 'طلب '.$application->reference_no)

@section('content')
<div class="employment-admin-shell">
    @if(session('employment_credentials_once'))
        @php($credentials = session('employment_credentials_once'))
        <section class="employment-credentials-once" role="alert"><div><span>بيانات دخول لمرة واحدة</span><h3>تم إنشاء حساب {{ $credentials['full_name'] }}</h3><p>سلّمها للموظف عبر قناة آمنة الآن؛ لن تظهر كلمة المرور مجددًا.</p></div><dl><div><dt>الرقم الوظيفي</dt><dd dir="ltr">{{ $credentials['employee_number'] }}</dd></div><div><dt>اسم المستخدم</dt><dd dir="ltr">{{ $credentials['username'] }}</dd></div><div><dt>كلمة المرور المؤقتة</dt><dd dir="ltr">{{ $credentials['password'] }}</dd></div></dl></section>
    @endif

    <section class="employment-profile-header"><div class="employment-applicant-monogram" aria-hidden="true">{{ mb_substr($application->full_name, 0, 1) }}</div><div><span dir="ltr">{{ $application->reference_no }}</span><h2>{{ $application->full_name }}</h2><p>{{ $application->job->title_ar }} · {{ $application->job->reference_no }}</p></div><span class="employment-status status-{{ $application->status }}">{{ config("employment.application_statuses.{$application->status}") }}</span><a class="btn btn-outline btn-sm" href="{{ route('dashboard.applications.index') }}">العودة إلى الطلبات</a></section>

    <div class="employment-detail-grid"><div class="employment-detail-main">
        <article class="panel employment-info-section"><header><span>01</span><h3>البيانات الشخصية والتواصل</h3></header><dl class="employment-data-grid">
            <div><dt>الاسم الكامل</dt><dd>{{ $application->full_name }}</dd></div><div><dt>الجنسية</dt><dd>{{ $application->nationality }}</dd></div><div><dt>نوع الهوية</dt><dd>{{ config("employment.identity_types.{$application->identity_type}") }}</dd></div><div><dt>رقم الهوية</dt><dd dir="ltr">{{ $application->identity_number }}</dd></div><div><dt>تاريخ الميلاد</dt><dd>{{ $application->birth_date->format('Y-m-d') }}</dd></div><div><dt>الجنس</dt><dd>{{ $application->gender === 'male' ? 'ذكر' : 'أنثى' }}</dd></div><div><dt>الجوال</dt><dd dir="ltr">{{ $application->mobile }}</dd></div><div><dt>البريد الإلكتروني</dt><dd dir="ltr">{{ $application->email }}</dd></div><div><dt>المدينة</dt><dd>{{ $application->city }}</dd></div><div class="span-2"><dt>العنوان</dt><dd>{!! nl2br(e($application->address)) !!}</dd></div>
        </dl></article>

        <article class="panel employment-info-section"><header><span>02</span><h3>المؤهلات والخبرة</h3></header><dl class="employment-data-grid">
            <div><dt>المؤهل</dt><dd>{{ config("employment.education_levels.{$application->education_level}") }}</dd></div><div><dt>التخصص</dt><dd>{{ $application->specialization }}</dd></div><div><dt>الجهة التعليمية</dt><dd>{{ $application->institution }}</dd></div><div><dt>سنة التخرج</dt><dd>{{ $application->graduation_year ?? '—' }}</dd></div><div><dt>سنوات الخبرة</dt><dd>{{ $application->experience_years }} سنة</dd></div><div><dt>الميناء المفضل</dt><dd>{{ $application->preferredPort?->name ?? 'غير محدد' }}</dd></div><div><dt>الجاهزية للمباشرة</dt><dd>{{ $application->availability_date?->format('Y-m-d') ?? 'غير محدد' }}</dd></div><div><dt>مصدر التعرف</dt><dd>{{ config("employment.sources.{$application->source}") }}</dd></div>
        </dl><div class="employment-prose-block"><h4>الملخص المهني</h4><p>{!! nl2br(e($application->professional_summary ?: 'لم يُضف المتقدم ملخصًا.')) !!}</p></div><div class="employment-prose-block"><h4>المهارات</h4><p>{!! nl2br(e($application->skills)) !!}</p></div><div class="employment-prose-block"><h4>خطاب التقديم</h4><p>{!! nl2br(e($application->cover_letter ?: 'لم يُضف المتقدم خطابًا.')) !!}</p></div></article>

        <article class="panel employment-info-section"><header><span>03</span><h3>المرفقات</h3></header>@if($application->attachments->isEmpty())<p class="employment-muted">لا توجد مرفقات محفوظة.</p>@else<div class="employment-attachment-list">@foreach($application->attachments as $attachment)<a href="{{ route('dashboard.attachments.download', $attachment) }}"><span>{{ config("employment.attachment_types.{$attachment->attachment_type}") }}</span><strong>{{ $attachment->original_name }}</strong><small>{{ number_format($attachment->file_size / 1024, 1) }} ك.ب · تنزيل آمن</small></a>@endforeach</div>@endif</article>

        @if($application->status === 'accepted' && $application->employee_user_id === null)
            <article class="panel employment-provision-panel"><header class="employment-section-heading"><div><span>الخطوة الأخيرة</span><h3>إنشاء حساب وبطاقة الموظف</h3></div></header><div class="employment-inline-notice">تُحفظ كلمة المرور مشفّرة وتظهر قيمتها مرة واحدة بعد نجاح العملية.</div>
                <form method="post" action="{{ route('dashboard.applications.provision', $application) }}" class="employment-form-grid" autocomplete="off">@csrf
                    <label>اسم المستخدم <b>*</b><input name="username" value="{{ old('username', $suggestedUsername) }}" minlength="4" maxlength="100" required dir="ltr"></label><label>كلمة المرور المؤقتة <b>*</b><input type="password" name="password" minlength="10" maxlength="200" required autocomplete="new-password" dir="ltr"></label><label>تاريخ المباشرة <b>*</b><input type="date" name="hire_date" value="{{ old('hire_date', now()->format('Y-m-d')) }}" required></label><label>القسم <b>*</b><select name="department_id" required><option value="">اختر القسم</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected((string) old('department_id') === (string) $department->id)>{{ $department->name }}</option>@endforeach</select></label>
                    <label>المسمى الوظيفي <b>*</b><select name="job_title_id" required><option value="">اختر المسمى</option>@foreach($jobTitles as $jobTitle)<option value="{{ $jobTitle->id }}" @selected((string) old('job_title_id') === (string) $jobTitle->id)>{{ $jobTitle->name }}</option>@endforeach</select></label><label>المدير المباشر<select name="manager_id"><option value="">بدون مدير مباشر</option>@foreach($managers as $manager)<option value="{{ $manager->id }}" @selected((string) old('manager_id') === (string) $manager->id)>{{ $manager->user->full_name }}</option>@endforeach</select></label><label>نوع العقد <b>*</b><select name="contract_type" required>@foreach(config('employment.contract_types') as $value => $label)<option value="{{ $value }}" @selected(old('contract_type', 'permanent') === $value)>{{ $label }}</option>@endforeach</select></label><label>بداية العقد <b>*</b><input type="date" name="contract_start_date" value="{{ old('contract_start_date', now()->format('Y-m-d')) }}" required></label><label>نهاية العقد<input type="date" name="contract_end_date" value="{{ old('contract_end_date') }}"></label><label>نهاية التجربة<input type="date" name="probation_end_date" value="{{ old('probation_end_date') }}"></label><label>ساعات العمل يوميًا <b>*</b><input type="number" name="working_hours_per_day" min="0.5" max="24" step="0.25" value="{{ old('working_hours_per_day', 8) }}" required></label><label>أيام العمل أسبوعيًا <b>*</b><input type="number" name="working_days_per_week" min="1" max="7" value="{{ old('working_days_per_week', 6) }}" required></label><label>الراتب الأساسي <b>*</b><input type="number" name="base_salary" min="0.01" max="9999999999.99" step="0.01" value="{{ old('base_salary', $application->job->salary_min) }}" required></label>
                    <label>ميناء التكليف<select name="port_id"><option value="">بدون تكليف</option>@foreach($ports as $port)<option value="{{ $port->id }}" @selected((string) old('port_id', $application->preferred_port_id ?: $application->job->port_id) === (string) $port->id)>{{ $port->governorate->name }} — {{ $port->name }}</option>@endforeach</select></label><label>المناوبة<select name="shift_id"><option value="">بدون تكليف</option>@foreach($shifts as $shift)<option value="{{ $shift->id }}" @selected((string) old('shift_id') === (string) $shift->id)>{{ $shift->name }}</option>@endforeach</select></label><div class="span-2 employment-form-actions"><button class="btn btn-primary" type="submit">إنشاء حساب الموظف</button></div>
                </form>
            </article>
        @endif
    </div>

    <aside class="employment-detail-side">
        <section class="panel employment-review-panel"><h3>قرار المراجعة</h3>@if(in_array($application->status, ['account_created', 'withdrawn'], true))<p class="employment-muted">هذه الحالة نهائية ولا يمكن تعديلها.</p>@else
            @php($availableStatuses = array_unique(array_merge([$application->status], \App\Models\EmploymentApplication::TRANSITIONS[$application->status] ?? [])))
            <form method="post" action="{{ route('dashboard.applications.review', $application) }}">@csrf @method('PATCH')<label>الحالة<select name="status">@foreach($availableStatuses as $status)<option value="{{ $status }}" @selected(old('status', $application->status) === $status)>{{ config("employment.application_statuses.{$status}") }}</option>@endforeach</select></label><label>ملاحظة المراجعة<textarea name="admin_note" rows="7" maxlength="5000">{{ old('admin_note', $application->admin_note) }}</textarea></label><button class="btn btn-primary" type="submit">حفظ المراجعة</button></form>
        @endif</section>
        <section class="panel employment-timeline"><h3>سجل الطلب</h3>@foreach($application->events as $event)<article><strong>{{ config("employment.application_statuses.{$event->to_status}", $event->event_type) }}</strong><small>{{ $event->created_at->format('Y-m-d H:i') }} · {{ $event->actor?->full_name ?? 'النظام' }}</small>@if($event->note)<p>{{ $event->note }}</p>@endif</article>@endforeach</section>
    </aside></div>
</div>
@endsection
