<?php

use App\Models\AuditLog;
use App\Models\Boat;
use App\Models\BusinessGlossaryTerm;
use App\Models\DataCatalogAsset;
use App\Models\DataLineageEdge;
use App\Models\DataQualityIssue;
use App\Models\FaoStandardMapping;
use App\Models\Fisher;
use App\Models\FishingSeason;
use App\Models\FishingSite;
use App\Models\GearType;
use App\Models\Governorate;
use App\Models\KpiRegistry;
use App\Models\Market;
use App\Models\MarketAuction;
use App\Models\Port;
use App\Models\Region;
use App\Models\SeasonLicense;
use App\Models\Species;
use App\Models\StatisticsOfficer;
use App\Models\UiTranslation;
use App\Models\UserPermission;

$statusOptions = ['نشط', 'متوقف', 'صيانة'];
$pressureOptions = ['طبيعي', 'مراقبة', 'ضغط مرتفع', 'إنذار'];

return [

    'regions' => [
        'label' => 'المناطق',
        'model' => Region::class,
        'title' => 'المناطق',
        'description' => 'المناطق الساحلية الرئيسية.',
        'columns' => ['name' => 'الاسم', 'code' => 'الرمز', 'coast_length_km' => 'طول الساحل (كم)', 'ports_count' => 'عدد الموانئ', 'total_catch_tons' => 'المصيد (طن)'],
        'fields' => [
            ['key' => 'name', 'label' => 'الاسم', 'required' => true],
            ['key' => 'code', 'label' => 'الرمز'],
            ['key' => 'coast_length_km', 'label' => 'طول الساحل (كم)', 'type' => 'number'],
            ['key' => 'governorates_count', 'label' => 'عدد المحافظات', 'type' => 'number'],
            ['key' => 'ports_count', 'label' => 'عدد الموانئ', 'type' => 'number'],
            ['key' => 'total_catch_tons', 'label' => 'إجمالي المصيد (طن)', 'type' => 'number'],
            ['key' => 'active_boats', 'label' => 'القوارب النشطة', 'type' => 'number'],
            ['key' => 'active_fishers', 'label' => 'الصيادون النشطون', 'type' => 'number'],
        ],
    ],

    'governorates' => [
        'label' => 'المحافظات',
        'model' => Governorate::class,
        'title' => 'المحافظات',
        'description' => 'المحافظات الساحلية وربطها بالمناطق.',
        'columns' => ['name' => 'الاسم', 'region' => 'المنطقة', 'coastal' => 'ساحلية', 'ports_count' => 'عدد الموانئ'],
        'fields' => [
            ['key' => 'name', 'label' => 'الاسم', 'required' => true],
            ['key' => 'region', 'label' => 'المنطقة', 'type' => 'select', 'options_from' => ['model' => Region::class, 'column' => 'name']],
            ['key' => 'coastal', 'label' => 'ساحلية', 'type' => 'boolean'],
            ['key' => 'ports_count', 'label' => 'عدد الموانئ', 'type' => 'number'],
            ['key' => 'total_catch_tons', 'label' => 'إجمالي المصيد (طن)', 'type' => 'number'],
            ['key' => 'active_boats', 'label' => 'القوارب النشطة', 'type' => 'number'],
            ['key' => 'active_fishers', 'label' => 'الصيادون النشطون', 'type' => 'number'],
        ],
    ],

    'ports' => [
        'label' => 'الموانئ',
        'model' => Port::class,
        'title' => 'الموانئ والمراسي',
        'description' => 'إدارة الموانئ وربطها بالمنطقة والمحافظة.',
        'columns' => ['name' => 'الاسم', 'code' => 'الرمز', 'region' => 'المنطقة', 'governorate' => 'المحافظة', 'boats_count' => 'القوارب', 'status' => 'الحالة'],
        'fields' => [
            ['key' => 'name', 'label' => 'الاسم', 'required' => true],
            ['key' => 'code', 'label' => 'الرمز'],
            ['key' => 'region', 'label' => 'المنطقة', 'type' => 'select', 'options_from' => ['model' => Region::class, 'column' => 'name']],
            ['key' => 'governorate', 'label' => 'المحافظة', 'type' => 'select', 'options_from' => ['model' => Governorate::class, 'column' => 'name']],
            ['key' => 'lat', 'label' => 'خط العرض', 'type' => 'number'],
            ['key' => 'lng', 'label' => 'خط الطول', 'type' => 'number'],
            ['key' => 'boats_count', 'label' => 'عدد القوارب', 'type' => 'number'],
            ['key' => 'active_boats', 'label' => 'القوارب النشطة', 'type' => 'number'],
            ['key' => 'fishers_count', 'label' => 'عدد الصيادين', 'type' => 'number'],
            ['key' => 'daily_trips', 'label' => 'الرحلات اليومية', 'type' => 'number'],
            ['key' => 'monthly_trips', 'label' => 'الرحلات الشهرية', 'type' => 'number'],
            ['key' => 'total_catch_tons', 'label' => 'إجمالي المصيد (طن)', 'type' => 'number'],
            ['key' => 'statistics_staff', 'label' => 'موظفو الإحصاء', 'type' => 'number'],
            ['key' => 'status', 'label' => 'الحالة', 'type' => 'select', 'options' => $statusOptions],
        ],
    ],

    'fishing-sites' => [
        'label' => 'مواقع الصيد',
        'model' => FishingSite::class,
        'title' => 'مواقع الصيد',
        'description' => 'مواقع الصيد وإحداثياتها وأقرب ميناء.',
        'columns' => ['name' => 'الاسم', 'region' => 'المنطقة', 'nearest_port' => 'أقرب ميناء', 'depth_m' => 'العمق (م)', 'pressure_level' => 'مستوى الضغط'],
        'badges' => ['pressure_level' => ['طبيعي' => 'ok', 'مراقبة' => 'warn', 'ضغط مرتفع' => 'danger', 'إنذار' => 'danger']],
        'fields' => [
            ['key' => 'name', 'label' => 'الاسم', 'required' => true],
            ['key' => 'lat', 'label' => 'خط العرض', 'type' => 'number'],
            ['key' => 'lng', 'label' => 'خط الطول', 'type' => 'number'],
            ['key' => 'region', 'label' => 'المنطقة', 'type' => 'select', 'options_from' => ['model' => Region::class, 'column' => 'name']],
            ['key' => 'nearest_port', 'label' => 'أقرب ميناء', 'type' => 'select', 'options_from' => ['model' => Port::class, 'column' => 'name']],
            ['key' => 'depth_m', 'label' => 'العمق (م)', 'type' => 'number'],
            ['key' => 'trips_count', 'label' => 'عدد الرحلات', 'type' => 'number'],
            ['key' => 'boats_count', 'label' => 'عدد القوارب', 'type' => 'number'],
            ['key' => 'catch_kg', 'label' => 'كمية المصيد (كجم)', 'type' => 'number'],
            ['key' => 'avg_catch_per_trip', 'label' => 'متوسط المصيد/رحلة', 'type' => 'number'],
            ['key' => 'pressure_level', 'label' => 'مستوى الضغط', 'type' => 'select', 'options' => $pressureOptions],
        ],
    ],

    'boats' => [
        'label' => 'القوارب',
        'model' => Boat::class,
        'title' => 'القوارب',
        'description' => 'أسطول الصيد ورخصه وحالته التشغيلية.',
        'columns' => ['name' => 'الاسم', 'boat_number' => 'رقم القارب', 'port' => 'الميناء', 'captain' => 'الكابتن', 'license_status' => 'الرخصة', 'status' => 'الحالة'],
        'badges' => ['license_status' => ['سارية' => 'ok', 'قريبة الانتهاء' => 'warn', 'منتهية' => 'danger']],
        'fields' => [
            ['key' => 'name', 'label' => 'اسم القارب', 'required' => true],
            ['key' => 'boat_number', 'label' => 'رقم القارب'],
            ['key' => 'port', 'label' => 'الميناء', 'type' => 'select', 'options_from' => ['model' => Port::class, 'column' => 'name']],
            ['key' => 'region', 'label' => 'المنطقة', 'type' => 'select', 'options_from' => ['model' => Region::class, 'column' => 'name']],
            ['key' => 'governorate', 'label' => 'المحافظة', 'type' => 'select', 'options_from' => ['model' => Governorate::class, 'column' => 'name']],
            ['key' => 'captain', 'label' => 'الكابتن'],
            ['key' => 'boat_type', 'label' => 'نوع القارب', 'type' => 'select', 'options' => ['قارب صغير', 'لنش', 'طراد', 'سفينة جر']],
            ['key' => 'length_m', 'label' => 'الطول (م)', 'type' => 'number'],
            ['key' => 'crew_capacity', 'label' => 'سعة الطاقم', 'type' => 'number'],
            ['key' => 'license_type', 'label' => 'نوع الرخصة', 'type' => 'select', 'options' => ['حرفي', 'تجاري', 'ترفيهي']],
            ['key' => 'license_number', 'label' => 'رقم الرخصة'],
            ['key' => 'license_expiry', 'label' => 'انتهاء الرخصة', 'type' => 'date'],
            ['key' => 'license_status', 'label' => 'حالة الرخصة', 'type' => 'select', 'options' => ['سارية', 'قريبة الانتهاء', 'منتهية']],
            ['key' => 'trips_count', 'label' => 'عدد الرحلات', 'type' => 'number'],
            ['key' => 'total_catch_kg', 'label' => 'إجمالي المصيد (كجم)', 'type' => 'number'],
            ['key' => 'violations_count', 'label' => 'عدد المخالفات', 'type' => 'number'],
            ['key' => 'status', 'label' => 'الحالة', 'type' => 'select', 'options' => ['نشط', 'متوقف', 'محظور', 'صيانة']],
        ],
    ],

    'fishers' => [
        'label' => 'الصيادون',
        'model' => Fisher::class,
        'title' => 'الصيادون',
        'description' => 'سجل الصيادين والكباتن وربطهم بالقوارب والموانئ.',
        'columns' => ['name' => 'الاسم', 'role' => 'الدور', 'port' => 'الميناء', 'boat' => 'القارب', 'experience_years' => 'الخبرة (سنة)', 'status' => 'الحالة'],
        'fields' => [
            ['key' => 'name', 'label' => 'الاسم', 'required' => true],
            ['key' => 'national_id', 'label' => 'رقم الهوية'],
            ['key' => 'phone', 'label' => 'الجوال'],
            ['key' => 'role', 'label' => 'الدور', 'type' => 'select', 'options' => ['صياد', 'كابتن', 'بحّار']],
            ['key' => 'port', 'label' => 'الميناء', 'type' => 'select', 'options_from' => ['model' => Port::class, 'column' => 'name']],
            ['key' => 'region', 'label' => 'المنطقة', 'type' => 'select', 'options_from' => ['model' => Region::class, 'column' => 'name']],
            ['key' => 'governorate', 'label' => 'المحافظة', 'type' => 'select', 'options_from' => ['model' => Governorate::class, 'column' => 'name']],
            ['key' => 'boat', 'label' => 'القارب', 'type' => 'select', 'options_from' => ['model' => Boat::class, 'column' => 'name']],
            ['key' => 'license_number', 'label' => 'رقم الرخصة'],
            ['key' => 'license_expiry', 'label' => 'انتهاء الرخصة', 'type' => 'date'],
            ['key' => 'experience_years', 'label' => 'سنوات الخبرة', 'type' => 'number'],
            ['key' => 'trips_count', 'label' => 'عدد الرحلات', 'type' => 'number'],
            ['key' => 'status', 'label' => 'الحالة', 'type' => 'select', 'options' => ['نشط', 'متوقف', 'موقوف']],
        ],
    ],

    'species' => [
        'label' => 'الأنواع السمكية',
        'model' => Species::class,
        'title' => 'الأنواع السمكية',
        'description' => 'دليل الأنواع المدقق مع الأسماء العلمية والمحلية وحالة المخزون.',
        'columns' => ['code' => 'الترميز', 'name_ar' => 'الاسم المحلي', 'name_sci' => 'الاسم العلمي', 'category' => 'التصنيف', 'status' => 'حالة المخزون'],
        'badges' => ['status' => ['مستقر' => 'ok', 'مراقبة' => 'warn', 'ضغط صيد مرتفع' => 'danger', 'انخفاض حاد' => 'danger']],
        'fields' => [
            ['key' => 'code', 'label' => 'الترميز', 'type' => 'number'],
            ['key' => 'name_ar', 'label' => 'الاسم المحلي', 'required' => true],
            ['key' => 'name_sci', 'label' => 'الاسم العلمي'],
            ['key' => 'corrected_name_sci', 'label' => 'الاسم العلمي المصحّح'],
            ['key' => 'name_en', 'label' => 'الاسم الإنجليزي'],
            ['key' => 'name_local_gulf', 'label' => 'الاسم المحلي – الخليج العربي'],
            ['key' => 'name_local_red_sea', 'label' => 'الاسم المحلي – البحر الأحمر'],
            ['key' => 'record_type', 'label' => 'نوع السجل', 'type' => 'select', 'options' => ['نوع سمك', 'عائلة/مجموعة']],
            ['key' => 'category', 'label' => 'التصنيف', 'type' => 'select', 'options' => ['أسماك', 'روبيان', 'قشريات', 'رخويات', 'أخرى']],
            ['key' => 'avg_weight_kg', 'label' => 'متوسط الوزن (كجم)', 'type' => 'number'],
            ['key' => 'avg_length_cm', 'label' => 'متوسط الحجم (سم)', 'type' => 'number'],
            ['key' => 'season', 'label' => 'موسم الصيد'],
            ['key' => 'regions', 'label' => 'مناطق الانتشار'],
            ['key' => 'top_port', 'label' => 'أكثر ميناء إنزالاً', 'type' => 'select', 'options_from' => ['model' => Port::class, 'column' => 'name']],
            ['key' => 'status', 'label' => 'حالة المخزون', 'type' => 'select', 'options' => ['مستقر', 'مراقبة', 'ضغط صيد مرتفع', 'انخفاض حاد']],
            ['key' => 'directory_status', 'label' => 'حالة الدليل', 'type' => 'select', 'options' => ['نشط', 'غير نشط']],
            ['key' => 'review_status', 'label' => 'حالة المراجعة العلمية', 'type' => 'select', 'options' => ['مصحح وموثق', 'منسق آليًا', 'مقبول مبدئيًا']],
            ['key' => 'source_1', 'label' => 'المصدر 1'],
            ['key' => 'source_2', 'label' => 'المصدر 2'],
            ['key' => 'review_date', 'label' => 'تاريخ المراجعة', 'type' => 'date'],
            ['key' => 'notes', 'label' => 'ملاحظات', 'type' => 'textarea'],
        ],
    ],

    'gear-types' => [
        'label' => 'أدوات الصيد',
        'model' => GearType::class,
        'title' => 'أدوات الصيد',
        'description' => 'أنواع أدوات الصيد وترميز ISSCFG ومواصفاتها.',
        'columns' => ['name' => 'الاسم', 'code' => 'الرمز', 'category' => 'التصنيف', 'isscfg_code' => 'ISSCFG', 'min_mesh_size_mm' => 'أصغر فتحة (مم)'],
        'fields' => [
            ['key' => 'name', 'label' => 'الاسم', 'required' => true],
            ['key' => 'code', 'label' => 'الرمز'],
            ['key' => 'category', 'label' => 'التصنيف', 'type' => 'select', 'options' => ['شباك', 'خطوط', 'أشراك', 'جر', 'أخرى']],
            ['key' => 'isscfg_code', 'label' => 'كود ISSCFG'],
            ['key' => 'min_mesh_size_mm', 'label' => 'أصغر فتحة عين (مم)', 'type' => 'number'],
            ['key' => 'selective', 'label' => 'انتقائية', 'type' => 'boolean'],
            ['key' => 'active', 'label' => 'نشط', 'type' => 'boolean'],
            ['key' => 'notes', 'label' => 'ملاحظات', 'type' => 'textarea'],
        ],
    ],

    'statistics-officers' => [
        'label' => 'موظفو الإحصاء',
        'model' => StatisticsOfficer::class,
        'title' => 'موظفو الإحصاء',
        'description' => 'فريق الإحصاء الميداني وتوزيعهم على الموانئ والورديات.',
        'columns' => ['name' => 'الاسم', 'employee_number' => 'الرقم الوظيفي', 'port' => 'الميناء', 'shift' => 'الوردية', 'trips_counted' => 'رحلات محصاة', 'status' => 'الحالة'],
        'fields' => [
            ['key' => 'name', 'label' => 'الاسم', 'required' => true],
            ['key' => 'employee_number', 'label' => 'الرقم الوظيفي'],
            ['key' => 'email', 'label' => 'البريد الإلكتروني'],
            ['key' => 'phone', 'label' => 'الجوال'],
            ['key' => 'port', 'label' => 'الميناء', 'type' => 'select', 'options_from' => ['model' => Port::class, 'column' => 'name']],
            ['key' => 'region', 'label' => 'المنطقة', 'type' => 'select', 'options_from' => ['model' => Region::class, 'column' => 'name']],
            ['key' => 'governorate', 'label' => 'المحافظة', 'type' => 'select', 'options_from' => ['model' => Governorate::class, 'column' => 'name']],
            ['key' => 'shift', 'label' => 'الوردية', 'type' => 'select', 'options' => ['صباحية', 'مسائية', 'ليلية']],
            ['key' => 'trips_counted', 'label' => 'الرحلات المحصاة', 'type' => 'number'],
            ['key' => 'status', 'label' => 'الحالة', 'type' => 'select', 'options' => ['نشط', 'متوقف']],
        ],
    ],

    'fishing-seasons' => [
        'label' => 'مواسم الصيد',
        'model' => FishingSeason::class,
        'title' => 'مواسم الصيد',
        'description' => 'مواسم الصيد وفترات الحظر والحصص المسموحة.',
        'columns' => ['name' => 'الموسم', 'species' => 'النوع', 'region' => 'المنطقة', 'start_date' => 'من', 'end_date' => 'إلى', 'status' => 'الحالة'],
        'badges' => ['status' => ['مفتوح' => 'ok', 'مغلق' => 'danger', 'قريب الفتح' => 'warn']],
        'fields' => [
            ['key' => 'name', 'label' => 'اسم الموسم', 'required' => true],
            ['key' => 'species', 'label' => 'النوع', 'type' => 'select', 'options_from' => ['model' => Species::class, 'column' => 'name_ar']],
            ['key' => 'region', 'label' => 'المنطقة', 'type' => 'select', 'options_from' => ['model' => Region::class, 'column' => 'name']],
            ['key' => 'season_type', 'label' => 'نوع الفترة', 'type' => 'select', 'options' => ['موسم صيد', 'فترة حظر']],
            ['key' => 'start_date', 'label' => 'تاريخ البداية', 'type' => 'date'],
            ['key' => 'end_date', 'label' => 'تاريخ النهاية', 'type' => 'date'],
            ['key' => 'gear_allowed', 'label' => 'الأدوات المسموحة'],
            ['key' => 'min_size_cm', 'label' => 'أصغر حجم مسموح (سم)', 'type' => 'number'],
            ['key' => 'quota_tons', 'label' => 'الحصة (طن)', 'type' => 'number'],
            ['key' => 'status', 'label' => 'الحالة', 'type' => 'select', 'options' => ['مفتوح', 'مغلق', 'قريب الفتح']],
            ['key' => 'notes', 'label' => 'ملاحظات', 'type' => 'textarea'],
        ],
    ],

    'season-licenses' => [
        'label' => 'رخص المواسم',
        'model' => SeasonLicense::class,
        'title' => 'رخص المواسم',
        'description' => 'رخص الصيد الموسمية المرتبطة بالقوارب والحصص.',
        'columns' => ['license_number' => 'رقم الرخصة', 'season' => 'الموسم', 'boat' => 'القارب', 'species' => 'النوع', 'quota_kg' => 'الحصة (كجم)', 'status' => 'الحالة'],
        'badges' => ['status' => ['سارية' => 'ok', 'منتهية' => 'danger', 'ملغاة' => 'danger', 'معلقة' => 'warn']],
        'fields' => [
            ['key' => 'license_number', 'label' => 'رقم الرخصة', 'required' => true],
            ['key' => 'season', 'label' => 'الموسم', 'type' => 'select', 'options_from' => ['model' => FishingSeason::class, 'column' => 'name']],
            ['key' => 'boat', 'label' => 'القارب', 'type' => 'select', 'options_from' => ['model' => Boat::class, 'column' => 'name']],
            ['key' => 'captain', 'label' => 'الكابتن'],
            ['key' => 'port', 'label' => 'الميناء', 'type' => 'select', 'options_from' => ['model' => Port::class, 'column' => 'name']],
            ['key' => 'region', 'label' => 'المنطقة', 'type' => 'select', 'options_from' => ['model' => Region::class, 'column' => 'name']],
            ['key' => 'species', 'label' => 'النوع', 'type' => 'select', 'options_from' => ['model' => Species::class, 'column' => 'name_ar']],
            ['key' => 'gear_type', 'label' => 'أداة الصيد', 'type' => 'select', 'options_from' => ['model' => GearType::class, 'column' => 'name']],
            ['key' => 'issue_date', 'label' => 'تاريخ الإصدار', 'type' => 'date'],
            ['key' => 'expiry_date', 'label' => 'تاريخ الانتهاء', 'type' => 'date'],
            ['key' => 'quota_kg', 'label' => 'الحصة (كجم)', 'type' => 'number'],
            ['key' => 'used_kg', 'label' => 'المستخدم (كجم)', 'type' => 'number'],
            ['key' => 'status', 'label' => 'الحالة', 'type' => 'select', 'options' => ['سارية', 'منتهية', 'ملغاة', 'معلقة']],
            ['key' => 'notes', 'label' => 'ملاحظات', 'type' => 'textarea'],
        ],
    ],

    'markets' => [
        'label' => 'الأسواق',
        'model' => Market::class,
        'title' => 'أسواق السمك',
        'description' => 'أسواق ومزادات السمك وربطها بالموانئ.',
        'columns' => ['name' => 'اسم السوق', 'region' => 'المنطقة', 'governorate' => 'المحافظة', 'market_type' => 'النوع', 'auction_stalls_count' => 'دكات المزاد', 'status' => 'الحالة'],
        'fields' => [
            ['key' => 'name', 'label' => 'اسم السوق', 'required' => true],
            ['key' => 'code', 'label' => 'رمز السوق'],
            ['key' => 'region', 'label' => 'المنطقة', 'type' => 'select', 'options_from' => ['model' => Region::class, 'column' => 'name']],
            ['key' => 'governorate', 'label' => 'المحافظة', 'type' => 'select', 'options_from' => ['model' => Governorate::class, 'column' => 'name']],
            ['key' => 'port', 'label' => 'الميناء', 'type' => 'select', 'options_from' => ['model' => Port::class, 'column' => 'name']],
            ['key' => 'market_type', 'label' => 'نوع السوق', 'type' => 'select', 'options' => ['مزاد', 'جملة', 'تجزئة', 'مركّب']],
            ['key' => 'fish_shops_count', 'label' => 'عدد محلات بيع السمك', 'type' => 'number'],
            ['key' => 'auction_stalls_count', 'label' => 'عدد دكات المزادات', 'type' => 'number'],
            ['key' => 'status', 'label' => 'الحالة', 'type' => 'select', 'options' => ['نشط', 'متعطل', 'مغلق']],
            ['key' => 'notes', 'label' => 'ملاحظات', 'type' => 'textarea'],
        ],
    ],

    'market-auctions' => [
        'label' => 'المزادات',
        'model' => MarketAuction::class,
        'title' => 'حركة المزادات',
        'description' => 'سجل المزادات اليومية والأسعار والكميات المبيعة.',
        'columns' => ['date' => 'التاريخ', 'market' => 'السوق', 'species' => 'النوع', 'sold_kg' => 'المبيع (كجم)', 'avg_price' => 'متوسط السعر', 'buyer_type' => 'نوع المشتري'],
        'fields' => [
            ['key' => 'market', 'label' => 'السوق', 'type' => 'select', 'options_from' => ['model' => Market::class, 'column' => 'name']],
            ['key' => 'date', 'label' => 'التاريخ', 'type' => 'date'],
            ['key' => 'species', 'label' => 'النوع', 'type' => 'select', 'options_from' => ['model' => Species::class, 'column' => 'name_ar']],
            ['key' => 'grade', 'label' => 'الدرجة', 'type' => 'select', 'options' => ['ممتاز', 'أولى', 'ثانية']],
            ['key' => 'offered_kg', 'label' => 'المعروض (كجم)', 'type' => 'number'],
            ['key' => 'sold_kg', 'label' => 'المبيع (كجم)', 'type' => 'number'],
            ['key' => 'min_price', 'label' => 'أدنى سعر', 'type' => 'number'],
            ['key' => 'max_price', 'label' => 'أعلى سعر', 'type' => 'number'],
            ['key' => 'avg_price', 'label' => 'متوسط السعر', 'type' => 'number'],
            ['key' => 'buyer_type', 'label' => 'نوع المشتري', 'type' => 'select', 'options' => ['تجزئة', 'جملة', 'مطاعم', 'تصدير']],
            ['key' => 'source_port', 'label' => 'ميناء المصدر', 'type' => 'select', 'options_from' => ['model' => Port::class, 'column' => 'name']],
            ['key' => 'notes', 'label' => 'ملاحظات', 'type' => 'textarea'],
        ],
    ],

    'user-permissions' => [
        'label' => 'صلاحيات المستخدمين',
        'model' => UserPermission::class,
        'title' => 'صلاحيات المستخدمين',
        'description' => 'الأدوار والنطاق الجغرافي المسموح لكل مستخدم.',
        'columns' => ['user_email' => 'البريد', 'full_name' => 'الاسم', 'role' => 'الدور', 'scope_level' => 'النطاق', 'region' => 'المنطقة', 'port' => 'الميناء'],
        'fields' => [
            ['key' => 'user_email', 'label' => 'البريد الإلكتروني', 'required' => true],
            ['key' => 'full_name', 'label' => 'الاسم الكامل'],
            ['key' => 'role', 'label' => 'الدور', 'type' => 'select', 'options' => ['admin', 'top_management', 'fisheries_admin', 'researcher', 'supervision', 'region_manager', 'governorate_manager', 'port_manager', 'user']],
            ['key' => 'scope_level', 'label' => 'مستوى النطاق', 'type' => 'select', 'options' => ['المملكة', 'المنطقة', 'المحافظة', 'الميناء']],
            ['key' => 'region', 'label' => 'المنطقة', 'type' => 'select', 'options_from' => ['model' => Region::class, 'column' => 'name']],
            ['key' => 'governorate', 'label' => 'المحافظة', 'type' => 'select', 'options_from' => ['model' => Governorate::class, 'column' => 'name']],
            ['key' => 'port', 'label' => 'الميناء', 'type' => 'select', 'options_from' => ['model' => Port::class, 'column' => 'name']],
            ['key' => 'can_approve', 'label' => 'صلاحية الاعتماد', 'type' => 'boolean'],
            ['key' => 'can_export', 'label' => 'صلاحية التصدير', 'type' => 'boolean'],
            ['key' => 'active', 'label' => 'نشط', 'type' => 'boolean'],
            ['key' => 'notes', 'label' => 'ملاحظات', 'type' => 'textarea'],
        ],
    ],

    'ui-translations' => [
        'label' => 'ترجمة الواجهة',
        'model' => UiTranslation::class,
        'title' => 'ترجمة الواجهة',
        'description' => 'كتالوج النصوص العربية ومقابلها الإنجليزي.',
        'columns' => ['source_ar' => 'النص العربي', 'target_en' => 'الترجمة الإنجليزية', 'context' => 'السياق', 'status' => 'الحالة'],
        'fields' => [
            ['key' => 'source_ar', 'label' => 'النص العربي', 'type' => 'textarea', 'required' => true],
            ['key' => 'target_en', 'label' => 'الترجمة الإنجليزية', 'type' => 'textarea'],
            ['key' => 'context', 'label' => 'السياق'],
            ['key' => 'status', 'label' => 'الحالة', 'type' => 'select', 'options' => ['مترجم', 'بحاجة مراجعة', 'مسودة']],
        ],
    ],

    'fao-mappings' => [
        'label' => 'ربط معايير FAO',
        'model' => FaoStandardMapping::class,
        'title' => 'ربط معايير FAO',
        'description' => 'مطابقة العناصر المحلية مع أكواد ASFIS وISSCAAP وISSCFG وغيرها.',
        'columns' => ['local_entity_type' => 'نوع العنصر', 'local_name_ar' => 'الاسم المحلي', 'fao_system' => 'المعيار', 'fao_code' => 'كود FAO', 'verification_status' => 'التحقق'],
        'badges' => ['verification_status' => ['محقق' => 'ok', 'مقترح' => 'warn', 'غير محقق' => 'danger', 'يحتاج مراجعة' => 'warn']],
        'fields' => [
            ['key' => 'local_entity_type', 'label' => 'نوع العنصر المحلي', 'type' => 'select', 'options' => ['Species', 'FishingSite', 'Boat', 'FishingGear', 'Port', 'Commodity', 'Other'], 'required' => true],
            ['key' => 'local_id', 'label' => 'المعرّف المحلي'],
            ['key' => 'local_name_ar', 'label' => 'الاسم العربي'],
            ['key' => 'local_name_en', 'label' => 'الاسم الإنجليزي'],
            ['key' => 'fao_system', 'label' => 'معيار FAO', 'type' => 'select', 'options' => ['ASFIS', 'ISSCAAP', 'FAO_MAJOR_FISHING_AREA', 'ISSCFG', 'ISSCFV', 'ISSCFC', 'PSMA', 'FIRMS', 'OTHER'], 'required' => true],
            ['key' => 'fao_code', 'label' => 'كود FAO'],
            ['key' => 'fao_name', 'label' => 'اسم FAO'],
            ['key' => 'scientific_name', 'label' => 'الاسم العلمي'],
            ['key' => 'source_url', 'label' => 'رابط المصدر'],
            ['key' => 'verification_status', 'label' => 'حالة التحقق', 'type' => 'select', 'options' => ['غير محقق', 'مقترح', 'محقق', 'يحتاج مراجعة']],
            ['key' => 'valid_from', 'label' => 'ساري من', 'type' => 'date'],
            ['key' => 'valid_to', 'label' => 'ساري إلى', 'type' => 'date'],
            ['key' => 'notes', 'label' => 'ملاحظات', 'type' => 'textarea'],
        ],
    ],

    'data-quality-issues' => [
        'label' => 'ملاحظات الجودة',
        'model' => DataQualityIssue::class,
        'title' => 'ملاحظات جودة البيانات',
        'description' => 'تذاكر الجودة المكتشفة ومسار معالجتها.',
        'columns' => ['entity_name' => 'الكيان', 'record_label' => 'السجل', 'category' => 'الفئة', 'severity' => 'الخطورة', 'status' => 'الحالة', 'assigned_to' => 'المسؤول'],
        'badges' => ['severity' => ['critical' => 'danger', 'warning' => 'warn']],
        'fields' => [
            ['key' => 'fingerprint', 'label' => 'البصمة الفنية', 'required' => true],
            ['key' => 'run_id', 'label' => 'معرّف الفحص'],
            ['key' => 'category', 'label' => 'الفئة', 'type' => 'select', 'options' => ['duplicate', 'relationship', 'completeness', 'geography', 'traceability', 'other'], 'required' => true],
            ['key' => 'severity', 'label' => 'الخطورة', 'type' => 'select', 'options' => ['warning', 'critical']],
            ['key' => 'entity_name', 'label' => 'الكيان', 'required' => true],
            ['key' => 'record_id', 'label' => 'معرّف السجل'],
            ['key' => 'record_label', 'label' => 'السجل'],
            ['key' => 'field_name', 'label' => 'الحقل'],
            ['key' => 'issue_message', 'label' => 'المشكلة', 'type' => 'textarea', 'required' => true],
            ['key' => 'status', 'label' => 'الحالة', 'type' => 'select', 'options' => ['مفتوحة', 'قيد المعالجة', 'بانتظار التحقق', 'تم الحل', 'استثناء مقبول']],
            ['key' => 'priority', 'label' => 'الأولوية', 'type' => 'select', 'options' => ['منخفضة', 'متوسطة', 'عالية', 'حرجة']],
            ['key' => 'assigned_to', 'label' => 'مسندة إلى'],
            ['key' => 'due_date', 'label' => 'تاريخ الاستحقاق', 'type' => 'date'],
            ['key' => 'resolution_note', 'label' => 'ملاحظة الحل', 'type' => 'textarea'],
        ],
    ],

    'catalog-assets' => [
        'label' => 'أصول البيانات',
        'model' => DataCatalogAsset::class,
        'title' => 'كتالوج أصول البيانات',
        'description' => 'سجل أصول البيانات ومالكيها ودرجة حساسيتها.',
        'columns' => ['asset_key' => 'المعرف الفني', 'name_ar' => 'الاسم', 'asset_type' => 'النوع', 'domain' => 'المجال', 'system' => 'النظام', 'sensitivity' => 'الحساسية'],
        'fields' => [
            ['key' => 'asset_key', 'label' => 'المعرف الفني', 'required' => true],
            ['key' => 'name_ar', 'label' => 'الاسم العربي'],
            ['key' => 'name_en', 'label' => 'الاسم الإنجليزي', 'required' => true],
            ['key' => 'asset_type', 'label' => 'نوع الأصل', 'type' => 'select', 'options' => ['Operational Entity', 'Master Data', 'Analytics Feed', 'Lakehouse', 'Warehouse', 'Semantic Model', 'Report', 'GIS Layer', 'AI Service', 'External Standard', 'Other'], 'required' => true],
            ['key' => 'domain', 'label' => 'مجال البيانات', 'type' => 'select', 'options' => ['Geography', 'Fleet', 'Species', 'Trips', 'Catch', 'Licenses', 'Fishers', 'Markets', 'Compliance', 'Analytics', 'GIS', 'AI', 'FAO', 'Other'], 'required' => true],
            ['key' => 'system', 'label' => 'النظام المصدر', 'type' => 'select', 'options' => ['HAWAT', 'Microsoft Fabric', 'Power BI', 'ArcGIS', 'FAO', 'External'], 'required' => true],
            ['key' => 'source_of_truth', 'label' => 'مصدر الحقيقة', 'type' => 'boolean'],
            ['key' => 'owner_email', 'label' => 'مالك البيانات'],
            ['key' => 'steward_email', 'label' => 'مسؤول البيانات'],
            ['key' => 'sensitivity', 'label' => 'الحساسية', 'type' => 'select', 'options' => ['عام', 'داخلي', 'مقيد', 'شخصي', 'حساس']],
            ['key' => 'contains_pii', 'label' => 'يحتوي بيانات شخصية', 'type' => 'boolean'],
            ['key' => 'refresh_mode', 'label' => 'التحديث', 'type' => 'select', 'options' => ['لحظي', 'كل ساعة', 'يومي', 'شهري', 'عند الطلب', 'غير منطبق']],
            ['key' => 'retention_note', 'label' => 'سياسة الاحتفاظ'],
            ['key' => 'purpose', 'label' => 'الغرض', 'type' => 'textarea'],
            ['key' => 'quality_controlled', 'label' => 'خاضع لفحص الجودة', 'type' => 'boolean'],
            ['key' => 'active', 'label' => 'نشط', 'type' => 'boolean'],
            ['key' => 'notes', 'label' => 'ملاحظات', 'type' => 'textarea'],
        ],
    ],

    'lineage-edges' => [
        'label' => 'مسارات البيانات',
        'model' => DataLineageEdge::class,
        'title' => 'مسارات البيانات',
        'description' => 'العلاقات بين أصول البيانات من المصدر إلى الاستخدام.',
        'columns' => ['source_asset_key' => 'من', 'target_asset_key' => 'إلى', 'transformation' => 'التحويل', 'refresh_mode' => 'التحديث'],
        'fields' => [
            ['key' => 'source_asset_key', 'label' => 'الأصل المصدر', 'type' => 'select', 'options_from' => ['model' => DataCatalogAsset::class, 'column' => 'asset_key'], 'required' => true],
            ['key' => 'target_asset_key', 'label' => 'الأصل الهدف', 'type' => 'select', 'options_from' => ['model' => DataCatalogAsset::class, 'column' => 'asset_key'], 'required' => true],
            ['key' => 'transformation', 'label' => 'نوع التحويل', 'type' => 'select', 'options' => ['Direct Copy', 'Aggregation', 'Join', 'Filter', 'Enrichment', 'AI Inference', 'Other']],
            ['key' => 'refresh_mode', 'label' => 'التحديث', 'type' => 'select', 'options' => ['لحظي', 'كل ساعة', 'يومي', 'شهري', 'عند الطلب']],
            ['key' => 'active', 'label' => 'نشط', 'type' => 'boolean'],
            ['key' => 'notes', 'label' => 'ملاحظات', 'type' => 'textarea'],
        ],
    ],

    'glossary-terms' => [
        'label' => 'مصطلحات الأعمال',
        'model' => BusinessGlossaryTerm::class,
        'title' => 'قاموس الأعمال',
        'description' => 'التعريفات المعتمدة للمصطلحات المستخدمة في التقارير.',
        'columns' => ['term_ar' => 'المصطلح', 'term_en' => 'English', 'domain' => 'المجال', 'owner_email' => 'المالك', 'status' => 'الحالة'],
        'fields' => [
            ['key' => 'term_ar', 'label' => 'المصطلح العربي', 'required' => true],
            ['key' => 'term_en', 'label' => 'المصطلح الإنجليزي'],
            ['key' => 'domain', 'label' => 'المجال', 'type' => 'select', 'options' => ['Geography', 'Fleet', 'Species', 'Trips', 'Catch', 'Licenses', 'Markets', 'Compliance', 'Analytics', 'Other']],
            ['key' => 'definition_ar', 'label' => 'التعريف العربي', 'type' => 'textarea'],
            ['key' => 'definition_en', 'label' => 'التعريف الإنجليزي', 'type' => 'textarea'],
            ['key' => 'owner_email', 'label' => 'المالك'],
            ['key' => 'related_entities', 'label' => 'الكيانات المرتبطة'],
            ['key' => 'status', 'label' => 'الحالة', 'type' => 'select', 'options' => ['معتمد', 'مسودة', 'بحاجة مراجعة']],
            ['key' => 'notes', 'label' => 'ملاحظات', 'type' => 'textarea'],
        ],
    ],

    'kpi-registry' => [
        'label' => 'سجل المؤشرات',
        'model' => KpiRegistry::class,
        'title' => 'سجل المؤشرات',
        'description' => 'تعريف المؤشرات ومعادلاتها ومصادرها وحالة اعتمادها.',
        'columns' => ['kpi_key' => 'المعرف', 'name_ar' => 'المؤشر', 'unit' => 'الوحدة', 'domain' => 'المجال', 'refresh_mode' => 'التحديث', 'certification_status' => 'الاعتماد'],
        'badges' => ['certification_status' => ['معتمد' => 'ok', 'مسودة' => 'warn', 'مرفوض' => 'danger']],
        'fields' => [
            ['key' => 'kpi_key', 'label' => 'معرّف المؤشر', 'required' => true],
            ['key' => 'name_ar', 'label' => 'اسم المؤشر', 'required' => true],
            ['key' => 'name_en', 'label' => 'الاسم الإنجليزي'],
            ['key' => 'domain', 'label' => 'المجال', 'type' => 'select', 'options' => ['Production', 'Sustainability', 'Compliance', 'Markets', 'Fleet', 'Other']],
            ['key' => 'unit', 'label' => 'وحدة القياس', 'type' => 'select', 'options' => ['كجم', 'طن', 'رحلة', 'قارب', 'نسبة %', 'ريال', 'عدد']],
            ['key' => 'formula', 'label' => 'المعادلة', 'type' => 'textarea'],
            ['key' => 'source_entities', 'label' => 'الكيانات المصدر'],
            ['key' => 'owner_email', 'label' => 'المالك'],
            ['key' => 'refresh_mode', 'label' => 'التحديث', 'type' => 'select', 'options' => ['لحظي', 'يومي', 'شهري', 'سنوي', 'عند الطلب']],
            ['key' => 'certification_status', 'label' => 'حالة الاعتماد', 'type' => 'select', 'options' => ['مسودة', 'معتمد', 'مرفوض']],
            ['key' => 'notes', 'label' => 'ملاحظات', 'type' => 'textarea'],
        ],
    ],

    'audit-logs' => [
        'label' => 'سجل العمليات',
        'model' => AuditLog::class,
        'title' => 'سجل العمليات',
        'description' => 'سجل غير قابل للتعديل لكل العمليات الحساسة في النظام.',
        'readonly' => true,
        'columns' => ['timestamp' => 'الوقت', 'action' => 'العملية', 'entity' => 'الكيان', 'user' => 'المستخدم', 'user_role' => 'الدور', 'details' => 'التفاصيل'],
        'fields' => [],
    ],

];