@extends('layouts.dashboard')

@section('title', 'مركز عمليات الميناء')
@section('body-class', 'jurisdiction-page')

@push('styles')
<link rel="stylesheet" href="{{ asset('assets/css/jurisdiction.css') }}">
@endpush

@section('content')
<div class="jurisdiction-shell port-shell">
    <header class="jurisdiction-hero"><div><span>PORT CONTROL ROOM</span><h1>مركز عمليات الميناء</h1><p>إسناد فرق الإحصاء، مراقبة القوارب، ومعالجة الرحلات ذات الفروقات من شاشة تشغيل واحدة.</p></div>@if(auth()->user()->role->code !== 'port_supervisor' && $ports->count() > 1)<form method="get" class="scope-filter"><label>الميناء<select name="port_id">@foreach($ports as $item)<option value="{{ $item->id }}" @selected($port?->id === $item->id)>{{ $item->name }} — {{ $item->governorate->name }}</option>@endforeach</select></label><button class="btn btn-primary" type="submit">فتح</button></form>@endif</header>

    @if(!$port)<section class="jurisdiction-empty">لا توجد موانئ نشطة ضمن نطاقك.</section>@else
        <section class="jurisdiction-context"><span>{{ $port->governorate->name }}</span><strong>{{ $port->name }}</strong><a href="{{ route('dashboard.harbors.show', $port) }}">بيانات المرفأ ←</a></section>
        <section class="jurisdiction-kpis">@foreach([['موظفو المناوبة','on_shift'],['متاحون','available'],['مشغولون','busy'],['متوقعة','expected'],['وصلت','arrived'],['قيد الإحصاء','counting'],['بانتظار المراجعة','pending_review'],['متوسط الانتظار (د)','average_wait']] as [$label,$key])<article><span>{{ $label }}</span><strong>{{ $kpi[$key] ?? 0 }}</strong></article>@endforeach</section>

        <section class="command-panel"><header><span>SHIFT ROSTER</span><h2>موظفو مناوبة اليوم</h2></header><div class="table-scroll"><table><thead><tr><th>الموظف</th><th>المناوبة</th><th>الحضور</th><th>الحالة</th><th>الرحلة الحالية</th><th>رحلات اليوم</th></tr></thead><tbody>@forelse($staff as $row)<tr><td>{{ $row['assignment']->employee->user->full_name }}</td><td>{{ config("attendance.shifts.{$row['assignment']->shift->name}") }}</td><td>{{ $row['attendance'] ? config("attendance.statuses.{$row['attendance']->status}") : 'لم يبدأ' }}</td><td><span class="state-chip {{ $row['current_trip'] ? 'is-busy' : (in_array($row['attendance']?->status, ['present','late'], true) ? 'is-ready' : 'is-off') }}">{{ $row['current_trip'] ? 'مشغول' : (in_array($row['attendance']?->status, ['present','late'], true) ? 'متاح' : 'غير متاح') }}</span></td><td dir="ltr">{{ $row['current_trip']?->trip_code ?? '—' }}</td><td>{{ $row['trips_today'] }}</td></tr>@empty<tr><td colspan="6">لا يوجد موظفون في مناوبة اليوم.</td></tr>@endforelse</tbody></table></div>
            @if($employees->isNotEmpty())<form method="post" action="{{ route('dashboard.port-operations.assignments.store', $port) }}" class="operation-form">@csrf<label>إضافة موظف<select name="employee_id" required><option value="">اختر موظفاً نشطاً</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->user->full_name }}</option>@endforeach</select></label><label>المناوبة<select name="shift_id" required>@foreach($shifts as $shift)<option value="{{ $shift->id }}">{{ config("attendance.shifts.{$shift->name}") }}</option>@endforeach</select></label><label class="check-label"><input type="checkbox" name="is_temporary" value="1"> تكليف بديل مؤقت</label><button class="btn btn-primary" type="submit">إضافة للمناوبة</button></form>@endif
        </section>

        <section class="jurisdiction-grid two">
            <article class="command-panel"><header><span>INBOUND</span><h2>القوارب المتوقع وصولها</h2></header><div class="trip-cards">@forelse($expectedTrips as $trip)<article><span dir="ltr">{{ $trip->trip_code }}</span><h3>{{ $trip->boat->name }}</h3><p>{{ $trip->captain->full_name }}</p><time dir="ltr">{{ $trip->expected_arrival?->format('Y/m/d H:i') ?? '—' }}</time></article>@empty<div class="jurisdiction-empty">لا توجد رحلات متوقعة.</div>@endforelse</div></article>
            <article class="command-panel"><header><span>ARRIVAL QUEUE</span><h2>القوارب الواصلة وقيد الإحصاء</h2></header><div class="trip-queue">@forelse($arrivedTrips as $trip)<article><div><span dir="ltr">{{ $trip->trip_code }}</span><h3>{{ $trip->boat->name }}</h3><small>{{ config("trips.statuses.{$trip->status}", $trip->status) }} · {{ $trip->actual_arrival?->format('H:i') }}</small></div><form method="post" action="{{ route('dashboard.port-operations.trips.assignment', [$port, $trip]) }}">@csrf @method('PATCH')<select name="employee_id" required><option value="">{{ $trip->assignedEmployee?->user?->full_name ?? 'إسناد موظف' }}</option>@foreach($availableStaff as $row)<option value="{{ $row['assignment']->employee_id }}">{{ $row['assignment']->employee->user->full_name }}</option>@endforeach</select><button class="btn btn-primary" type="submit">{{ $trip->status === 'counting' ? 'تغيير' : 'بدء الإحصاء' }}</button></form>@if($trip->discrepancies->where('review_status', '!=', 'approved')->isNotEmpty())<form method="post" action="{{ route('dashboard.port-operations.trips.review', [$port, $trip]) }}">@csrf @method('PATCH')<button class="btn btn-outline" type="submit">تحويل للمراجعة</button></form>@endif</article>@empty<div class="jurisdiction-empty">لا توجد قوارب في قائمة الوصول.</div>@endforelse</div></article>
        </section>

        <section class="command-panel review-panel"><header><span>DISCREPANCY GATE</span><h2>رحلات بانتظار اعتماد الفرق</h2></header><div class="table-scroll"><table><thead><tr><th>الرحلة</th><th>القارب</th><th>فرق كجم</th><th>النسبة</th><th>الخطورة</th><th>الإجراء</th></tr></thead><tbody>@forelse($reviewTrips as $trip)@php($discrepancy = $trip->discrepancies->first())<tr><td dir="ltr">{{ $trip->trip_code }}</td><td>{{ $trip->boat->name }}</td><td>{{ number_format($discrepancy->diff_kg, 1) }}</td><td>{{ number_format($discrepancy->diff_percent, 1) }}%</td><td><span class="state-chip is-busy">{{ config("discrepancies.severities.{$discrepancy->severity}", $discrepancy->severity) }}</span></td><td><form method="post" action="{{ route('dashboard.port-operations.discrepancies.approve', [$port, $discrepancy]) }}">@csrf @method('PATCH')<button class="btn btn-primary" type="submit">اعتماد الفرق</button></form></td></tr>@empty<tr><td colspan="6">لا توجد فروقات تنتظر اعتماد الميناء.</td></tr>@endforelse</tbody></table></div></section>
    @endif
</div>
@endsection
